In [3]:
import numpy as np
import pandas as pd
import os
os.chdir('../')
from gravity import Gravity, Production, Attraction, Doubly, BaseGravity
import statsmodels.formula.api as smf
from statsmodels.api import families
import matplotlib.pyplot as plt
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [4]:
n = 50
o = np.tile(np.arange(n),n)
d = np.repeat(np.arange(n),n)
loc_size = np.random.randint(25000,500000, n)
o_vars = np.tile(loc_size, n)
d_vars = np.repeat(loc_size, n)
dij = np.random.exponential(2500, n**2)
f = o_vars**.3*d_vars**.4*np.exp(dij*-.00005)
o = np.reshape(o, (-1,1))
d = np.reshape(d, (-1,1))
o_vars = np.reshape(o_vars, (-1,1))
d_vars = np.reshape(d_vars, (-1,1))
dij = np.reshape(dij, (-1,1))
f = np.reshape(f, (-1,1))
f = f.astype(np.int64)

In [18]:
%time Gravity(f, o_vars, d_vars, dij, 'exp').params


CPU times: user 3.22 ms, sys: 679 µs, total: 3.9 ms
Wall time: 3.22 ms


array([  2.99989253e-01,   4.00002847e-01,  -5.00069377e-05])

In [8]:
data = pd.DataFrame({'o':o.flatten(), 'd':d.flatten(), 'o_vars':o_vars.flatten(), 'd_vars':d_vars.flatten(), 'dij':dij.flatten(), 'f':f.flatten()})

    

In [23]:
model = Doubly(f, o, d, dij, 'exp')

In [24]:
model.params[-1]

-5.0005299143593245e-05

In [25]:
local = model.local()

NotImplementedError: Local models not possible for doubly-constrained model due to insufficient  degrees of freedom.

In [19]:
local.keys()

['pvalue0',
 'deviance',
 'pvalue1',
 'tvalue0',
 'tvalue1',
 'param1',
 'param0',
 'aic']

In [6]:
model.dv

array([[443028],
       [443028],
       [443028],
       ..., 
       [ 52207],
       [ 52207],
       [ 52207]])

In [77]:
results = {}
covs = d_vars.shape[1] + 1
results['aic'] = []
results['deviance'] = []
for cov in range(covs):
    results['param' + str(cov)] = []
    results['pvalue' + str(cov)] = []
    results['tvalue' + str(cov)] = []
for origin in np.unique(o):
    print origin
    subset = (o == origin) | (o == origin+1)
    fl = np.reshape(f[subset], (-1,1))
    os = np.reshape(o[subset], (-1,1))
    ds = np.reshape(d[subset], (-1,1))
    d_v = np.reshape(d_vars[subset], (-1,1))
    o_v = np.reshape(o_vars[subset], (-1,1))
    c = np.reshape(dij[subset], (-1,1))
    model = Doubly(fl, os, ds, c, 'exp')
    results['aic'].append(model.aic)
    results['deviance'].append(model.deviance)
    for cov in range(covs):
        results['param' + str(cov)].append(model.params[cov])
        results['pvalue' + str(cov)].append(model.pvalues[cov])
        results['tvalue' + str(cov)].append(model.tvalues[cov])



0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49


Exception: one or more input arrays have more columns than rows

In [79]:
results

{'aic': [1158.8879722109086,
  1128.5747773753847,
  1128.9942403452133,
  1146.3823908024533,
  1114.3597580290661,
  1096.2504742314668,
  1122.9690796395043,
  1116.2922228138523,
  1115.8544535178225,
  1148.9616190636189,
  1142.2781303154479,
  1129.8979251113924,
  1129.3873687723499,
  1128.2294353908037,
  1112.6722994509437,
  1129.8398943337106,
  1156.8053041722233,
  1156.0694801329446,
  1149.5272988040124,
  1141.9098868169676,
  1150.2969021403405,
  1156.216777065456,
  1155.3793052859983,
  1143.1693342845465,
  1141.10993379309,
  1141.0134570111768,
  1135.0314874493524,
  1124.8169251647996,
  1132.8878224088912,
  1146.0067887993791,
  1135.7162203456792,
  1146.4982049525534,
  1155.9312319925702,
  1155.4433621531825,
  1141.5174825534195,
  1136.7901916521187,
  1146.9052164958266,
  1133.6638870723327,
  1135.377276446241,
  1149.4038210565632,
  1140.5408112245423,
  1124.0651406630932,
  1133.0625628929811,
  1145.8016409162919,
  1123.4304496287386,
  1133.

In [46]:
os

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0])

In [75]:
os.shape

(50, 1)