In [1]:
#import sys
#sys.path.append('/Users/toshan/dev/pysal/pysal/contrib/glm')
#from utils import 
import numpy as np
import pandas as pd
import sys
sys.path.append('/Users/toshan/dev/pysal/pysal/contrib/spint')
from gravity import Gravity, Production, Attraction, Doubly, BaseGravity
import gravity
from spint_utils import sorensen
import statsmodels.formula.api as smf
from statsmodels.api import families as families

In [2]:
austria = pd.read_csv('http://dl.dropbox.com/u/8649795/AT_Austria.csv')
austria = austria[austria['Origin'] != austria['Destination']]
f = austria['Data'].values
o = austria['Origin'].values
d = austria['Destination'].values
dij = austria['Dij'].values
o_vars = austria['Oi2007'].values
d_vars = austria['Dj2007'].values

In [3]:
grav = Gravity(f, o_vars, d_vars, dij, 'exp', framework='glm')
print grav.params

gravity = smf.glm('Data~np.log(Oi2007)+np.log(Dj2007)+Dij-1', family=families.Poisson(), data=austria).fit()
print gravity.params.values

[ 0.44051324  0.5144978  -0.00976746]
[ 0.44051324  0.5144978  -0.00976746]


In [4]:
production = Production(f, o, d_vars, dij, 'exp', framework='glm')
print production.params

gravity = smf.glm('Data~Origin+np.log(Dj2007)+Dij-1', family=families.Poisson(), data=austria).fit()
print gravity.params.values

[-1.11700938  0.5696138   1.03487752 -0.51400641 -0.23320154  0.09225167
 -0.42761955  0.03771866 -0.0922097   0.89278717 -0.00727113]
[-1.11700938  0.56961379  1.03487751 -0.51400641 -0.23320154  0.09225166
 -0.42761955  0.03771866 -0.0922097   0.89278717 -0.00727113]


In [5]:
attraction = Attraction(f, d, o_vars, dij, 'exp', framework='glm')
print attraction.params

gravity = smf.glm('Data~np.log(Oi2007)+Destination + Dij-1', family=families.Poisson(), data=austria).fit()
print gravity.params.values

[-0.88439723  0.73740882  1.04332355 -0.75977722 -0.26060911 -0.1879365
 -0.67530313 -0.19871953 -0.39900098  0.89235874 -0.00693755]
[-0.88439723  0.73740882  1.04332355 -0.75977722 -0.26060911 -0.1879365
 -0.67530313 -0.19871953 -0.39900099  0.89235874 -0.00693755]


In [6]:
doubly = Doubly(f, o, d, dij, 'exp', framework='glm')
print doubly.params[-1:]

gravity = smf.glm('Data~Origin+Destination+Dij-1', family=families.Poisson(), data=austria).fit()
print gravity.params.values[-1:]

[-0.00791533]
[-0.00791533]


In [7]:
sorensen(grav)

0.68822035942795623

In [8]:
sorensen(production)

0.74061920338298048

In [9]:
sorensen(attraction)

0.75063449829283135

In [10]:
sorensen(doubly)

0.81185211090388831

In [11]:
grav.SSI

0.68822035942795623

In [12]:
production.SSI

0.74061920338298048

In [13]:
attraction.SSI

0.75063449829283135

In [14]:
doubly.SSI

0.81185211090388831

In [15]:
grav.srmse

23.103958298546722

In [16]:
doubly.srmse

26.41275121188659

In [17]:
production.srmse

26.023881688328146

In [18]:
grav.pseudoR2

0.81258943875040157

In [19]:
production.pseudoR2

0.9099205901109565

In [20]:
doubly.pseudoR2


0.94353991219813327

In [21]:
grav.adj_pseudoR2

0.81255536218830349

In [21]:
grav.D2

0.83445652029136452

In [22]:
grav.adj_D2

0.82965815856067948

In [23]:
doubly.D2

0.94666192089648937

In [24]:
doubly.adj_D2

0.92987030340093968

In [123]:
y = grav.y
yhat = grav.yhat
n = grav.n

In [124]:
(np.sum((yhat-y)**2)/n)**.5

28741.324123392122

In [125]:
y = production.y
yhat = production.yhat
n = production.n


In [126]:
np.sqrt(np.sum((y-yhat)**2)/n) 


32373.708820280212

In [127]:
y = doubly.y
yhat = doubly.yhat
n = doubly.n

In [128]:
np.sqrt(np.sum((y-yhat)**2)/n) 

32857.462507586919

In [39]:
len(doubly.y)

72

In [41]:
doubly.n

72

In [42]:
np.mean(doubly.y)

1244.0972222222222

In [46]:
np.sqrt(np.mean((y-yhat)**2))

3872.2890919495749

In [47]:
yhat

array([  9.78988280e+02,   2.26003279e+03,   1.04038742e+02,
         3.38382580e+02,   1.90458075e+02,   8.67908467e+01,
         4.37554720e+01,   1.35532201e+01,   1.02693176e+03,
         1.43579537e+04,   5.02646536e+02,   1.61314478e+03,
         1.60124044e+03,   5.84144805e+02,   2.98377549e+02,
         9.55604104e+01,   2.92086883e+03,   1.76899160e+04,
         9.49267467e+02,   3.14910952e+03,   2.73315395e+03,
         1.01972797e+03,   5.15779061e+02,   1.64177257e+02,
         1.73496758e+02,   7.99088484e+02,   1.22486311e+03,
         9.31563443e+02,   6.29698756e+02,   5.91117070e+02,
         4.15424488e+02,   1.31747905e+02,   4.49674437e+02,
         2.04361676e+03,   3.23802841e+03,   7.42345992e+02,
         1.00234547e+03,   6.00432512e+02,   3.13590596e+02,
         9.69658353e+01,   3.29132064e+02,   2.63792996e+03,
         3.65458094e+03,   6.52540343e+02,   1.30346098e+03,
         1.16517842e+03,   6.73203489e+02,   2.21973821e+02,
         1.47356669e+02,

In [64]:
np.sqrt(np.sum(((y-yhat)**2)/n)) / np.sum(y/n)

26.799427831357789

In [90]:
np.sqrt(np.sum((y-yhat)**2)/n) / np.sum(y)/float(n)

0.005019646605929266

In [88]:
np.sum(y)/float(n)

1244.0972222222222

In [86]:
np.mean(y)

1244.0972222222222

In [130]:
np.nan * -1

nan

In [132]:
np.nan == np.nan

False

In [ ]:
np