In [1]:
#Import GLM and pysal
import os
import numpy as np
#os.chdir('/Users/qszhao/Dropbox/pysal/pysal/contrib/gwr')
os.chdir('/Users/toshan/dev/pysal/pysal/contrib/glm')
from glm import GLM
import pysal
import pandas as pd
import statsmodels.formula.api as smf
import statsmodels.api as sm
import family
#from statsmodels.api import families as family

In [2]:
#Prepare some test data - columbus example
db = pysal.open(pysal.examples.get_path('columbus.dbf'),'r')
y = np.array(db.by_col("HOVAL"))
y = np.reshape(y, (49,1))
X = []
#X.append(np.ones(len(y)))
X.append(db.by_col("INC"))
X.append(db.by_col("CRIME"))
X = np.array(X).T


In [3]:
#First fit pysal OLS model
from pysal.spreg import ols
OLS = ols.OLS(y, X)
print OLS.betas

[[ 46.42818268]
 [  0.62898397]
 [ -0.48488854]]


In [4]:
#Then fit Gaussian GLM

#create Gaussian GLM model object
model = GLM(y, X, family.Gaussian())
model

#Fit model to estimate coefficients and return GLMResults object
results = model.fit()

#Check coefficients - R betas [46.4282, 0.6290, -0.4849]
print results.betas.T

# Gaussian GLM results from statsmodels
sm_results = smf.OLS(y, sm.add_constant(X), ).fit()
print sm_results.params

[[ 0.]
 [ 0.]
 [ 0.]]
[[ 46.42818268]
 [  0.62898397]
 [ -0.48488854]]
[[ 46.42818268]
 [  0.62898397]
 [ -0.48488854]]
[[ 46.42818268]
 [  0.62898397]
 [ -0.48488854]]
[[ 46.42818268]
 [  0.62898397]
 [ -0.48488854]]
[[ 46.42818268]
 [  0.62898397]
 [ -0.48488854]]
[[ 46.42818268]
 [  0.62898397]
 [ -0.48488854]]
[[ 46.42818268]
 [  0.62898397]
 [ -0.48488854]]
[[ 46.42818268]
 [  0.62898397]
 [ -0.48488854]]
[[ 46.42818268]
 [  0.62898397]
 [ -0.48488854]]
[[ 46.42818268]
 [  0.62898397]
 [ -0.48488854]]
[[ 46.42818268]
 [  0.62898397]
 [ -0.48488854]]
[[ 46.42818268   0.62898397  -0.48488854]]
[ 46.42818268   0.62898397  -0.48488854]


In [5]:
#Now fit a Poisson GLM 

poisson_y = np.round(y)

#create Poisson GLM model object
model = GLM(y, X, family.Poisson())
model

#Fit model to estimate coefficients and return GLMResults object
results = model.fit()

#Check coefficients - R betas [3.91926, 0.01198, -0.01371]
print results.betas.T

# Poisson GLM results from statsmodels
sm_results = smf.GLM(y, sm.add_constant(X), family=family.Poisson()).fit()
print sm_results.params

[[ 0.]
 [ 0.]
 [ 0.]]
[[ 3.92373156]
 [ 0.01264334]
 [-0.01335153]]
[[ 3.91911347]
 [ 0.01199726]
 [-0.01369886]]
[[ 3.91925944]
 [ 0.01198276]
 [-0.01370719]]
[[ 3.91925951]
 [ 0.01198275]
 [-0.0137072 ]]
[[ 3.91925951]
 [ 0.01198275]
 [-0.0137072 ]]
[[ 3.91925951]
 [ 0.01198275]
 [-0.0137072 ]]
[[ 3.91925951]
 [ 0.01198275]
 [-0.0137072 ]]
[[ 3.91925951]
 [ 0.01198275]
 [-0.0137072 ]]
[[ 3.91925951]
 [ 0.01198275]
 [-0.0137072 ]]
[[ 3.91925951]
 [ 0.01198275]
 [-0.0137072 ]]
[[ 3.91925951]
 [ 0.01198275]
 [-0.0137072 ]]
[[ 3.91925951  0.01198275 -0.0137072 ]]
[ 3.91925951  0.01198275 -0.0137072 ]


In [6]:
#Now fit a binomial GLM
londonhp = pd.read_csv('/Users/toshan/projects/londonhp.csv')
#londonhp = pd.read_csv('/Users/qszhao/Dropbox/pysal/pysal/contrib/gwr/londonhp.csv')
y = londonhp['BATH2'].values
y = np.reshape(y, (316,1))
X = londonhp['FLOORSZ'].values
X = np.reshape(X, (316,1))

#create logistic GLM model object
model = GLM(y, X, family.Binomial())
model

#Fit model to estimate coefficients and return GLMResults object
results = model.fit()

#Check coefficients - R betas [-5.33638, 0.02878]
print results.betas.T

# Logistic GLM results from statsmodels
sm_results = smf.GLM(y, sm.add_constant(X), family=family.Binomial()).fit()
print sm_results.params

[[ 0.]
 [ 0.]]
[[-3.28539648]
 [ 0.01460839]]
[[-4.684064 ]
 [ 0.0244298]]
[[-5.25187088]
 [ 0.02821449]]
[[-5.33484113]
 [ 0.02876519]]
[[-5.33638224]
 [ 0.0287754 ]]
[[-5.33638276]
 [ 0.0287754 ]]
[[-5.33638276]
 [ 0.0287754 ]]
[[-5.33638276]
 [ 0.0287754 ]]
[[-5.33638276]
 [ 0.0287754 ]]
[[-5.33638276]
 [ 0.0287754 ]]
[[-5.33638276]
 [ 0.0287754 ]]
[[-5.33638276  0.0287754 ]]
[-5.33638276  0.0287754 ]
