In [1]:
#Import GLM and pysal
import os
import numpy as np
os.chdir('/Users/toshan/dev/pysal/pysal/contrib/glm')
from glm import GLM
import pysal
import pandas as pd
import statsmodels.formula.api as smf
import statsmodels.api as sm
from family import Gaussian, Binomial, Poisson, QuasiPoisson

from statsmodels.api import families

In [2]:
#Prepare some test data - columbus example
db = pysal.open(pysal.examples.get_path('columbus.dbf'),'r')
y = np.array(db.by_col("HOVAL"))
y = np.reshape(y, (49,1))
X = []
#X.append(np.ones(len(y)))
X.append(db.by_col("INC"))
X.append(db.by_col("CRIME"))
X = np.array(X).T

In [3]:
#First fit pysal OLS model
from pysal.spreg import ols
OLS = ols.OLS(y, X)
print OLS.betas

[[ 46.42818268]
 [  0.62898397]
 [ -0.48488854]]


In [4]:
#Then fit Gaussian GLM

#create Gaussian GLM model object
model = GLM(y, X, Gaussian())
model

#Fit model to estimate coefficients and return GLMResults object
results = model.fit()

#Check coefficients - R betas [46.4282, 0.6290, -0.4849]
print results.params

# Gaussian GLM results from statsmodels
sm_model = smf.GLM(y, sm.add_constant(X), family=families.Gaussian())
sm_results = sm_model.fit()
print sm_results.params

<class 'family.Gaussian'>
<class 'family.Gaussian'>
<class 'family.Gaussian'>
[ 46.42818268   0.62898397  -0.48488854]
[ 46.42818268   0.62898397  -0.48488854]


In [5]:
print results.df_model, sm_results.df_model
print np.allclose(results.aic, sm_results.aic)
print np.allclose(results.bic, sm_results.bic)
print np.allclose(results.deviance, sm_results.deviance)
print np.allclose(results.df_model, sm_results.df_model)
print np.allclose(results.df_resid, sm_results.df_resid)
print np.allclose(results.llf, sm_results.llf)
print np.allclose(results.mu, sm_results.mu)
print np.allclose(results.n, sm_results.nobs)
print np.allclose(results.null, sm_results.null)
print np.allclose(results.null_deviance, sm_results.null_deviance)
print np.allclose(results.params, sm_results.params)
print np.allclose(results.pearson_chi2, sm_results.pearson_chi2)
print np.allclose(results.resid_anscombe, sm_results.resid_anscombe)
print np.allclose(results.resid_deviance, sm_results.resid_deviance)
print np.allclose(results.resid_pearson, sm_results.resid_pearson)
print np.allclose(results.resid_response, sm_results.resid_response)
print np.allclose(results.resid_working, sm_results.resid_working)
print np.allclose(results.scale, sm_results.scale)
print np.allclose(results.normalized_cov_params, sm_results.normalized_cov_params)
print np.allclose(results.cov_params(), sm_results.cov_params())
print np.allclose(results.bse, sm_results.bse)
print np.allclose(results.conf_int(), sm_results.conf_int())
print np.allclose(results.pvalues, sm_results.pvalues)
print np.allclose(results.tvalues, sm_results.tvalues)


2 2
<class 'family.Gaussian'>
True
True
True
True
True
True
True
True
<class 'family.Gaussian'>
<class 'family.Gaussian'>
<class 'family.Gaussian'>
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True


In [6]:
#Now fit a Poisson GLM 

poisson_y = np.round(y).astype(int)

#create Poisson GLM model object
model = GLM(poisson_y, X, Poisson())
model

#Fit model to estimate coefficients and return GLMResults object
results = model.fit()

#Check coefficients - R betas [3.91926, 0.01198, -0.01371]
print results.params.T

# Poisson GLM results from statsmodels
sm_results = smf.GLM(poisson_y, sm.add_constant(X), family=families.Poisson()).fit()
print sm_results.params

<class 'family.Poisson'>
<class 'family.Poisson'>
<class 'family.Poisson'>
[ 3.92159085  0.01183491 -0.01371397]
[ 3.92159085  0.01183491 -0.01371397]


In [7]:
print np.allclose(results.aic, sm_results.aic)
print np.allclose(results.bic, sm_results.bic)
print np.allclose(results.deviance, sm_results.deviance)
print np.allclose(results.df_model, sm_results.df_model)
print np.allclose(results.df_resid, sm_results.df_resid)
print np.allclose(results.llf, sm_results.llf)
print np.allclose(results.mu, sm_results.mu)
print np.allclose(results.n, sm_results.nobs)
print np.allclose(results.null, sm_results.null)
print np.allclose(results.null_deviance, sm_results.null_deviance)
print np.allclose(results.params, sm_results.params)
print np.allclose(results.pearson_chi2, sm_results.pearson_chi2)
print np.allclose(results.resid_anscombe, sm_results.resid_anscombe)
print np.allclose(results.resid_deviance, sm_results.resid_deviance)
print np.allclose(results.resid_pearson, sm_results.resid_pearson)
print np.allclose(results.resid_response, sm_results.resid_response)
print np.allclose(results.resid_working, sm_results.resid_working)
print np.allclose(results.scale, sm_results.scale)
print np.allclose(results.normalized_cov_params, sm_results.normalized_cov_params)
print np.allclose(results.cov_params(), sm_results.cov_params())
print np.allclose(results.bse, sm_results.bse)
print np.allclose(results.conf_int(), sm_results.conf_int())
print np.allclose(results.pvalues, sm_results.pvalues)
print np.allclose(results.tvalues, sm_results.tvalues)
print results.bse, sm_results.bse

<class 'family.Poisson'>
True
True
True
True
True
True
True
True
<class 'family.Poisson'>
<class 'family.Poisson'>
<class 'family.Poisson'>
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
[ 0.13049161  0.00511599  0.00193769] [ 0.13049161  0.00511599  0.00193769]


In [82]:
#Now fit a binomial GLM
londonhp = pd.read_csv('/Users/toshan/projects/londonhp.csv')
#londonhp = pd.read_csv('/Users/qszhao/Dropbox/pysal/pysal/contrib/gwr/londonhp.csv')
y = londonhp['BATH2'].values
y = np.reshape(y, (316,1))
X = londonhp['FLOORSZ'].values
X = np.reshape(X, (316,1))

#create logistic GLM model object
model = GLM(y, X, Binomial())
model

#Fit model to estimate coefficients and return GLMResults object
results = model.fit()

#Check coefficients - R betas [-5.33638, 0.02878]
print results.params.T

# Logistic GLM results from statsmodels
sm_results = smf.GLM(y, sm.add_constant(X), family=families.Binomial()).fit()
print sm_results.params

[-5.33638276  0.0287754 ]
[-5.33638276  0.0287754 ]


In [76]:
print results.df_model, sm_results.df_model
print np.allclose(results.aic, sm_results.aic)
print np.allclose(results.bic, sm_results.bic)
print np.allclose(results.deviance, sm_results.deviance)
print np.allclose(results.df_model, sm_results.df_model)
print np.allclose(results.df_resid, sm_results.df_resid)
print np.allclose(results.llf, sm_results.llf)
print np.allclose(results.mu, sm_results.mu)
print np.allclose(results.n, sm_results.nobs)
print np.allclose(results.null, sm_results.null)
print np.allclose(results.null_deviance, sm_results.null_deviance)
print np.allclose(results.params, sm_results.params)
print np.allclose(results.pearson_chi2, sm_results.pearson_chi2)
print np.allclose(results.resid_anscombe, sm_results.resid_anscombe)
print np.allclose(results.resid_deviance, sm_results.resid_deviance)
print np.allclose(results.resid_pearson, sm_results.resid_pearson)
print np.allclose(results.resid_response, sm_results.resid_response)
print np.allclose(results.resid_working, sm_results.resid_working)
print np.allclose(results.scale, sm_results.scale)
print np.allclose(results.normalized_cov_params, sm_results.normalized_cov_params)
print np.allclose(results.cov_params(), sm_results.cov_params())
print np.allclose(results.bse, sm_results.bse)
print np.allclose(results.conf_int(), sm_results.conf_int())
print np.allclose(results.pvalues, sm_results.pvalues)
print np.allclose(results.tvalues, sm_results.tvalues)


1 1
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True


In [10]:
#create QUasiPoisson GLM model object
model = GLM(poisson_y, X, QuasiPoisson())
model

#Fit model to estimate coefficients and return GLMResults object
results = model.fit()

<class 'family.QuasiPoisson'>
<class 'family.QuasiPoisson'>
<class 'family.QuasiPoisson'>
