In [38]:
import scipy.spatial
import pysal as ps
import numpy as np

In [39]:
run distance_statistics

In [40]:
p1.min_nnd

8.9958712752017522

In [41]:
p1.mean_nnd

21.792944822977631

In [42]:
p1.max_nnd

34.63124167568931

In [43]:
p2.knn(2)

(array([[1, 4],
        [3, 4],
        [4, 3],
        [1, 4],
        [2, 3]]), array([[ 44.86326448,  44.89484603],
        [ 15.64542745,  38.60403735],
        [ 21.11125292,  54.61691771],
        [ 15.64542745,  36.05221907],
        [ 21.11125292,  36.05221907]]))

In [44]:
p2.G()

array([[  0.        ,   0.        ],
       [  4.48632645,   0.        ],
       [  8.9726529 ,   0.        ],
       [ 13.45897934,   0.        ],
       [ 17.94530579,   0.4       ],
       [ 22.43163224,   0.8       ],
       [ 26.91795869,   0.8       ],
       [ 31.40428514,   0.8       ],
       [ 35.89061159,   0.8       ],
       [ 40.37693803,   0.8       ],
       [ 44.86326448,   0.8       ],
       [ 49.34959093,   1.        ]])

In [45]:
p1.G(10)

array([[  0.        ,   0.        ],
       [  3.46312417,   0.        ],
       [  6.92624834,   0.        ],
       [ 10.3893725 ,   0.16666667],
       [ 13.85249667,   0.16666667],
       [ 17.31562084,   0.25      ],
       [ 20.77874501,   0.25      ],
       [ 24.24186917,   0.58333333],
       [ 27.70499334,   0.83333333],
       [ 31.16811751,   0.83333333],
       [ 34.63124168,   1.        ],
       [ 38.09436584,   1.        ]])

In [46]:
p1.G(25)

array([[  0.        ,   0.        ],
       [  1.38524967,   0.        ],
       [  2.77049933,   0.        ],
       [  4.155749  ,   0.        ],
       [  5.54099867,   0.        ],
       [  6.92624834,   0.        ],
       [  8.311498  ,   0.        ],
       [  9.69674767,   0.16666667],
       [ 11.08199734,   0.16666667],
       [ 12.467247  ,   0.16666667],
       [ 13.85249667,   0.16666667],
       [ 15.23774634,   0.16666667],
       [ 16.622996  ,   0.25      ],
       [ 18.00824567,   0.25      ],
       [ 19.39349534,   0.25      ],
       [ 20.77874501,   0.25      ],
       [ 22.16399467,   0.58333333],
       [ 23.54924434,   0.58333333],
       [ 24.93449401,   0.75      ],
       [ 26.31974367,   0.83333333],
       [ 27.70499334,   0.83333333],
       [ 29.09024301,   0.83333333],
       [ 30.47549267,   0.83333333],
       [ 31.86074234,   0.83333333],
       [ 33.24599201,   0.91666667],
       [ 34.63124168,   1.        ],
       [ 36.01649134,   1.        ]])

In [47]:
c =np.vstack((a,b)).T

In [48]:
c

array([[  0.        ,   0.        ],
       [  3.46312417,   0.        ],
       [  6.92624834,   0.        ],
       [ 10.3893725 ,   0.16666667],
       [ 13.85249667,   0.16666667],
       [ 17.31562084,   0.25      ],
       [ 20.77874501,   0.25      ],
       [ 24.24186917,   0.58333333],
       [ 27.70499334,   0.83333333],
       [ 31.16811751,   0.83333333],
       [ 34.63124168,   1.        ],
       [ 38.09436584,   1.        ]])

In [49]:
p1.knn_other(p2, k=1)

(array([[10],
        [10],
        [10],
        [10],
        [10]]), array([[ 108.83047597],
        [  64.84924826],
        [ 110.79904918],
        [  58.96644809],
        [  94.49216105]]))

In [50]:
p2.knn_other(p1, k=1)

(array([[3],
        [1],
        [1],
        [1],
        [1],
        [3],
        [3],
        [1],
        [3],
        [3],
        [1],
        [3]]), array([[ 107.55869514],
        [ 141.42135624],
        [ 100.34875435],
        [ 145.35741949],
        [ 110.88855532],
        [  79.81676328],
        [ 126.9858248 ],
        [ 140.93209606],
        [  51.61964452],
        [  90.6541571 ],
        [  64.84924826],
        [ 134.3210769 ]]))

In [51]:
points

[[66.22, 32.54],
 [22.52, 22.39],
 [31.01, 81.21],
 [9.47, 31.02],
 [30.78, 60.1],
 [75.21, 58.93],
 [79.26, 7.68],
 [8.23, 39.93],
 [98.73, 80.53],
 [89.78, 42.53],
 [65.19, 92.08],
 [54.46, 8.48]]

In [54]:
p2.J()

NotImplemented

In [53]:
po = Point_Pattern(points)
po.tree

In [ ]:
po.knn()

In [ ]:
po.knn(k=2)

In [ ]:
po.knn_other([[7,7]])

In [ ]:
po.find_pairs(20.0)

In [ ]:
po.points

In [ ]:
nn_ids(points)

In [ ]:
k3 = knn(points, 3)
k3[0]

In [ ]:
k3[1]

In [ ]:
%pylab inline

In [ ]:
import numpy as np
points = np.array(points)
scatter(points[:,0], points[:,1])
#xlim([0,100])
#ylim([0,100])

In [ ]:
40 / 10.

In [ ]:
G_bf(points)

In [ ]:
nn_distances(points)

In [ ]:
 mbr_bf(points)

In [ ]:
F_bf(points)

In [ ]:
G = G_bf(points)

In [ ]:
F_cdf = F_cdf_bf(points)

In [ ]:
F_cdf = np.array(F_cdf).T

In [ ]:
scatter(F_cdf[:,0], F_cdf[:,1])
xlim(0,40)
ylim(0,1.0)

In [ ]:
G = np.array(G).T

In [ ]:
scatter(G[:,0], G[:,1])
xlim(0,40)
ylim(0,1.)

In [ ]:
plot(G[:,0], G[:,1],label='G')
F = F_cdf
plot(F[:,0], F[:,1], label='F')
legend(loc='lower right')

In [ ]:
k_bf(points)

In [ ]:
12*12 - 12

In [ ]:
np.random.poisson(1.5)

In [ ]:
c = csr_bf(mbr_bf(points), 12)

In [ ]:
c

In [ ]:
cl = csr_bf(mbr_bf(points),12, n_conditioned=False)

In [ ]:
cl

In [ ]:
import shapely