In [21]:
import numpy as np
import pysal as ps
from pysal.weights.Distance import Kernel
import sys
sys.path.append('/Users/toshan/dev/pysal/pysal/weights')
from Distance import Kernel as kn
from util import full2W as f2w
from kernels import _Kernel
import scipy.spatial.distance as sp

In [13]:
m

3

In [14]:
n = 3 #number of observations
m = 3 #number of calibration points

In [15]:
x = np.random.randint(1,1000, n)
y = np.random.randint(1,1000, n)
D1 = zip(x,y)
W1 = kn(D1, function='gaussian', truncate=False)

In [16]:
x = np.random.randint(1,1000, m)
y = np.random.randint(1,1000, m)
D2 = zip(x,y)
W2 = kn(D2, function='gaussian', truncate=False)

In [17]:
D3 = np.vstack([D1,D2])
D3

array([[726, 270],
       [871, 131],
       [204, 614],
       [310, 616],
       [104,  91],
       [137, 441]])

In [18]:
D3 = np.vstack([D1,D2])
W3 = kn(D3, function='gaussian', truncate=False)

W3.full()[0][n:,:-m].T

array([[ 0.30570919,  0.27258174,  0.28338823],
       [ 0.24197075,  0.23334113,  0.2239938 ],
       [ 0.39488618,  0.30828906,  0.38665182]])

In [19]:
W4 = _Kernel(D3, function='gaussian', truncate=False, k=2)
W4.kernel[n:,:-m].T

array([[ 0.30570919,  0.27258174,  0.28338823],
       [ 0.24197075,  0.23334113,  0.2239938 ],
       [ 0.39488618,  0.30828906,  0.38665182]])

In [22]:
W5 = sp.cdist(D3,D3)
W5[n:,:-m].T

array([[ 541.08409698,  647.24415795,  613.32047088],
       [ 741.58344102,  768.04231654,  796.77851377],
       [ 106.01886625,  532.47441253,  185.52088831]])

In [23]:
W6 = W4.dmat
W6[n:,:-m].T

array([[ 541.08409698,  647.24415795,  613.32047088],
       [ 741.58344102,  768.04231654,  796.77851377],
       [ 106.01886625,  532.47441253,  185.52088831]])

In [26]:
W4[5]

TypeError: '_Kernel' object does not support indexing

In [317]:

coord_ids = np.arange(n)
points_ids = np.arange(n, n+m)
all_ids = np.arange(n+m)
dists = np.zeros((m,n))


for i in all_ids:
    print i
    if i in points_ids:
        for j in coord_ids:
            if j in W3[j].keys():
                if i >= n:
                    print 'a'
                    dists[i-n][j] = W3.full()[0][i][j]
                elif j >= m:
                    print 'b'
                    dists[i][j-m] = W3.full()[0][i][j]
                elif (i >= n) & (j >= m):
                    print 'c'
                    dists[i-n][j-m] = W3.full()[0][i][j]
                else:
                    print 'd'
                    dists[i][j] = W3.full()[0][i][j]



0
1
2
3
4
5
a
a
a
a
a
6
a
a
a
a
a
7
a
a
a
a
a


In [84]:
W3.transform = 'v'
W3.full()[0]

array([[ 0.18517132,  0.12031966,  0.13646984,  0.15290816,  0.07164861,
         0.09212782,  0.17278679,  0.11213752],
       [ 0.1429542 ,  0.22000575,  0.13344025,  0.07452373,  0.07270798,
         0.08211464,  0.09860256,  0.1813038 ],
       [ 0.17702068,  0.14568467,  0.24019338,  0.09798799,  0.02731182,
         0.03856209,  0.13308669,  0.08379397],
       [ 0.16605976,  0.06811897,  0.0820388 ,  0.20109788,  0.09148889,
         0.11815657,  0.19465287,  0.08493308],
       [ 0.08481599,  0.07244222,  0.02492489,  0.09972512,  0.21920158,
         0.213782  ,  0.09167339,  0.14716403],
       [ 0.10206486,  0.07656773,  0.03293508,  0.12053401,  0.20007215,
         0.20514417,  0.11186615,  0.14248252],
       [ 0.17822579,  0.08560278,  0.10582965,  0.18487878,  0.07987913,
         0.10415336,  0.19100017,  0.09294788],
       [ 0.12375274,  0.16840325,  0.07129012,  0.08630719,  0.13719415,
         0.1419319 ,  0.09944509,  0.20435139]])

In [66]:
dists

array([[ 0.19848475,  0.14890067,  0.06404859,  0.23440155,  0.38907876],
       [ 0.37226043,  0.17879864,  0.22104651,  0.38615654,  0.16684364],
       [ 0.24159463,  0.32876301,  0.13917518,  0.16849206,  0.26783546]])

In [74]:
subset_dists = dists[0:m,0:n]
subset_dists

array([[ 0.19848475,  0.14890067,  0.06404859,  0.23440155,  0.38907876],
       [ 0.37226043,  0.17879864,  0.22104651,  0.38615654,  0.16684364],
       [ 0.24159463,  0.32876301,  0.13917518,  0.16849206,  0.26783546]])

In [80]:
x1, y1 = D1[0]
x2, y2 = D2[0]
print kn(np.sqrt((x1-x2)**2 + (y1-y2)**2))

ValueError: Buffer has wrong number of dimensions (expected 2, got 1)

In [44]:
w = f2w(dists)
w.full()[0]

ValueError: Your array is not square

In [45]:
new_neighbs = {}
new_weights = {}
for each in W2.neighbors:
    three = set(W3.neighbors[each])
    two = set(W2.neighbors[each])
    new_neighbs[each] = list(three.difference(two))
    new_weights[each] = {}
    for weight in new_neighbs[each]:
        new_weights[each][weight] = W3[each][weight]

In [46]:
coord_ids = W1.id_order
points_ids = W2.id_order
all_ids = W3.id_order
dists = np.zeros((2,3))

'''
for ids in all_ids:
    if ids in points_ids:
        _all = set(W3.neighbors[ids])
        points = set(W2.neighbors[ids])
        new_neighbs[ids] = list(_all.difference(points))
        new_weights[ids] = {}
        for weight in new_neighbs[ids]:
            new_weights[ids][weight] = W3[ids][weight]

    else:
        new_weights[ids] = {}
'''       


'\nfor ids in all_ids:\n    if ids in points_ids:\n        _all = set(W3.neighbors[ids])\n        points = set(W2.neighbors[ids])\n        new_neighbs[ids] = list(_all.difference(points))\n        new_weights[ids] = {}\n        for weight in new_neighbs[ids]:\n            new_weights[ids][weight] = W3[ids][weight]\n\n    else:\n        new_weights[ids] = {}\n'

In [47]:
n = 3 #number of observations
m = 2 #number of 
for i in all_ids:
    if i in points_ids:
        for j in coord_ids:
            if j in W3[j].keys():
                print i,j
                if i >= n:
                    print 'a'
                    dists[i-n][j] = W3.full()[0][i][j]
                elif j >= m:
                    print 'b'
                    dists[i][j-m] = W3.full()[0][i][j]
                elif (i >= n) & (j >= m):
                    print 'c'
                    dists[i-n][j-m] = W3.full()[0][i][j]
                else:
                    print 'd'
                    dists[i][j] = W3.full()[0][i][j]


0 0
d
0 1
d
0 2
b
0 3
b
0 4
b
1 0
d
1 1
d
1 2
b
1 3
b
1 4
b
2 0
d


IndexError: index 2 is out of bounds for axis 0 with size 2

In [48]:
dists

array([[ 0.16030707,  0.17179277,  0.27299611],
       [ 0.24747341,  0.25108674,  0.16263902]])

In [49]:
points_ids

[0, 1, 2]

In [50]:
W4 = ps.W(new_neighbs, new_weights)

In [52]:
W4.full()[0]

ValueError: 3 is not in list

In [165]:
coord_ids = np.arange(n)
points_ids = np.arange(m)
dists = np.zeros((n,m))

for i in coord_ids:
    for j in points_ids:
        x1,x2 = D1[i]
        x2,y2 = D2[j]
        dists[i,j] = np.sqrt((x1-x2)**2 + (y1-y2)**2)

In [88]:
dists

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [163]:
for i in coord_ids:
    for j in points_ids:
        x1,x2 = D1[i]
        x2,y2 = D2[j]
        dists[i,j] = np.sqrt((x1-x2)**2 + (y1-y2)**2)

In [164]:
dists

array([[ 642.13705702,  588.5414174 ,  263.10454196],
       [ 636.88303479,  602.8573629 ,  258.56527222],
       [ 759.82695398,  387.65964453,  410.03048667],
       [ 682.13268504,  502.22704029,  308.64380765],
       [ 829.12001544,  318.40383164,  499.12323128]])

In [151]:
a,b,c = W1.full()[0], W2.full()[0], W3.full()[0]

In [152]:
a.shape

(5, 5)

In [153]:
b.shape

(3, 3)

In [154]:
c.shape

(8, 8)

In [155]:
[x for x in a.flatten() if x in c]

[0.3989422804014327,
 0.3989422804014327,
 0.3989422804014327,
 0.3989422804014327,
 0.3989422804014327]

In [156]:
[x for x in b.flatten() if x in c]

[0.3989422804014327, 0.3989422804014327, 0.3989422804014327]

In [157]:
a

array([[ 0.39894228,  0.32549582,  0.24197075,  0.36131425,  0.28654809],
       [ 0.32549582,  0.39894228,  0.11166935,  0.22743353,  0.29339103],
       [ 0.24197075,  0.11166935,  0.39894228,  0.34184938,  0.17571081],
       [ 0.36131425,  0.22743353,  0.34184938,  0.39894228,  0.25633142],
       [ 0.28654809,  0.29339103,  0.17571081,  0.25633142,  0.39894228]])

In [160]:
import scipy.spatial.distance as sp

In [161]:
sp.cdist(D3, D3)

array([[    0.        ,   313.40867888,   491.3023509 ,   218.69156362,
          399.68612685,   533.56630328,   649.85690733,   376.04919891],
       [  313.40867888,     0.        ,   784.01594372,   520.85410625,
          385.1700923 ,   825.10847772,   545.50985326,    85.27602242],
       [  491.3023509 ,   784.01594372,     0.        ,   273.05677065,
          629.16532009,   464.88815859,   857.68525696,   857.93997459],
       [  218.69156362,   520.85410625,   273.05677065,     0.        ,
          462.10929443,   430.99071916,   718.0250692 ,   590.427811  ],
       [  399.68612685,   385.1700923 ,   629.16532009,   462.10929443,
            0.        ,   886.01580121,   258.31182706,   465.72524089],
       [  533.56630328,   825.10847772,   464.88815859,   430.99071916,
          886.01580121,     0.        ,  1144.09309062,   864.76123872],
       [  649.85690733,   545.50985326,   857.68525696,   718.0250692 ,
          258.31182706,  1144.09309062,     0.        ,   

In [179]:
sp.cdist(D1, D2)

array([[ 533.56630328,  649.85690733,  376.04919891],
       [ 825.10847772,  545.50985326,   85.27602242],
       [ 464.88815859,  857.68525696,  857.93997459],
       [ 430.99071916,  718.0250692 ,  590.427811  ],
       [ 886.01580121,  258.31182706,  465.72524089]])

In [184]:


coord_ids = np.arange(n)
points_ids = np.arange(m)
dists = np.zeros((n,m))

for i in coord_ids:
    for j in points_ids:
        x1,y1 = D1[i]
        x2,y2 = D2[j]
        dists[i,j] = np.sqrt((x2-x1)**2 + (y2-y1)**2)

In [185]:
dists

array([[ 533.56630328,  649.85690733,  376.04919891],
       [ 825.10847772,  545.50985326,   85.27602242],
       [ 464.88815859,  857.68525696,  857.93997459],
       [ 430.99071916,  718.0250692 ,  590.427811  ],
       [ 886.01580121,  258.31182706,  465.72524089]])

In [173]:
n

5

In [174]:
m

3

In [186]:
a

array([[ 0.39894228,  0.32549582,  0.24197075,  0.36131425,  0.28654809],
       [ 0.32549582,  0.39894228,  0.11166935,  0.22743353,  0.29339103],
       [ 0.24197075,  0.11166935,  0.39894228,  0.34184938,  0.17571081],
       [ 0.36131425,  0.22743353,  0.34184938,  0.39894228,  0.25633142],
       [ 0.28654809,  0.29339103,  0.17571081,  0.25633142,  0.39894228]])

In [187]:
b

array([[ 0.39894228,  0.24197075,  0.29981427],
       [ 0.24197075,  0.39894228,  0.34653252],
       [ 0.29981427,  0.34653252,  0.39894228]])

In [188]:
c

array([[ 0.39894228,  0.33824743,  0.26593447,  0.36813835,  0.30502818,
         0.24726767,  0.19622043,  0.31457187],
       [ 0.33824743,  0.39894228,  0.14202752,  0.25289972,  0.31092348,
         0.12709312,  0.24197075,  0.39409745],
       [ 0.26593447,  0.14202752,  0.39894228,  0.35196789,  0.20514264,
         0.27746287,  0.11590961,  0.11582453],
       [ 0.36813835,  0.25289972,  0.35196789,  0.39894228,  0.27866639,
         0.29198776,  0.1677652 ,  0.22209064],
       [ 0.30502818,  0.31092348,  0.20514264,  0.27866639,  0.39894228,
         0.10667727,  0.356632  ,  0.27709994],
       [ 0.24726767,  0.12709312,  0.27746287,  0.29198776,  0.10667727,
         0.39894228,  0.04423435,  0.1135601 ],
       [ 0.19622043,  0.24197075,  0.11590961,  0.1677652 ,  0.356632  ,
         0.04423435,  0.39894228,  0.21471537],
       [ 0.31457187,  0.39409745,  0.11582453,  0.22209064,  0.27709994,
         0.1135601 ,  0.21471537,  0.39894228]])

In [193]:
a = sp.cdist(D1,D1)
a

array([[   0.        ,  313.40867888,  491.3023509 ,  218.69156362,
         399.68612685],
       [ 313.40867888,    0.        ,  784.01594372,  520.85410625,
         385.1700923 ],
       [ 491.3023509 ,  784.01594372,    0.        ,  273.05677065,
         629.16532009],
       [ 218.69156362,  520.85410625,  273.05677065,    0.        ,
         462.10929443],
       [ 399.68612685,  385.1700923 ,  629.16532009,  462.10929443,    0.        ]])

In [194]:
b = sp.cdist(D2,D2)
b

array([[    0.        ,  1144.09309062,   864.76123872],
       [ 1144.09309062,     0.        ,   607.21083653],
       [  864.76123872,   607.21083653,     0.        ]])

In [197]:
c = sp.cdist(D3,D3)
c

array([[    0.        ,   313.40867888,   491.3023509 ,   218.69156362,
          399.68612685,   533.56630328,   649.85690733,   376.04919891],
       [  313.40867888,     0.        ,   784.01594372,   520.85410625,
          385.1700923 ,   825.10847772,   545.50985326,    85.27602242],
       [  491.3023509 ,   784.01594372,     0.        ,   273.05677065,
          629.16532009,   464.88815859,   857.68525696,   857.93997459],
       [  218.69156362,   520.85410625,   273.05677065,     0.        ,
          462.10929443,   430.99071916,   718.0250692 ,   590.427811  ],
       [  399.68612685,   385.1700923 ,   629.16532009,   462.10929443,
            0.        ,   886.01580121,   258.31182706,   465.72524089],
       [  533.56630328,   825.10847772,   464.88815859,   430.99071916,
          886.01580121,     0.        ,  1144.09309062,   864.76123872],
       [  649.85690733,   545.50985326,   857.68525696,   718.0250692 ,
          258.31182706,  1144.09309062,     0.        ,   

In [201]:
d = [x for x in a.flatten() if x in c]
d

[0.0,
 313.40867888429636,
 491.30235090013565,
 218.69156362329116,
 399.68612685456071,
 313.40867888429636,
 0.0,
 784.0159437154324,
 520.85410625241309,
 385.17009229689683,
 491.30235090013565,
 784.0159437154324,
 0.0,
 273.05677065401619,
 629.1653200868592,
 218.69156362329116,
 520.85410625241309,
 273.05677065401619,
 0.0,
 462.10929443152298,
 399.68612685456071,
 385.17009229689683,
 629.1653200868592,
 462.10929443152298,
 0.0]

In [202]:
e = [x for x in b.flatten() if x in c]
e

[0.0,
 1144.0930906180668,
 864.76123872430821,
 1144.0930906180668,
 0.0,
 607.21083653044275,
 864.76123872430821,
 607.21083653044275,
 0.0]

In [204]:
g = d + e

In [205]:
len(g)

34

In [210]:
for x in g:
    if x in c:
        print 'True'

True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True


In [209]:
for x in g:
    print x

0.0
313.408678884
491.3023509
218.691563623
399.686126855
313.408678884
0.0
784.015943715
520.854106252
385.170092297
491.3023509
784.015943715
0.0
273.056770654
629.165320087
218.691563623
520.854106252
273.056770654
0.0
462.109294432
399.686126855
385.170092297
629.165320087
462.109294432
0.0
0.0
1144.09309062
864.761238724
1144.09309062
0.0
607.21083653
864.761238724
607.21083653
0.0


In [213]:
len(c.flatten())

64

In [214]:
a

array([[   0.        ,  313.40867888,  491.3023509 ,  218.69156362,
         399.68612685],
       [ 313.40867888,    0.        ,  784.01594372,  520.85410625,
         385.1700923 ],
       [ 491.3023509 ,  784.01594372,    0.        ,  273.05677065,
         629.16532009],
       [ 218.69156362,  520.85410625,  273.05677065,    0.        ,
         462.10929443],
       [ 399.68612685,  385.1700923 ,  629.16532009,  462.10929443,    0.        ]])

In [215]:
b

array([[    0.        ,  1144.09309062,   864.76123872],
       [ 1144.09309062,     0.        ,   607.21083653],
       [  864.76123872,   607.21083653,     0.        ]])

In [216]:
c

array([[    0.        ,   313.40867888,   491.3023509 ,   218.69156362,
          399.68612685,   533.56630328,   649.85690733,   376.04919891],
       [  313.40867888,     0.        ,   784.01594372,   520.85410625,
          385.1700923 ,   825.10847772,   545.50985326,    85.27602242],
       [  491.3023509 ,   784.01594372,     0.        ,   273.05677065,
          629.16532009,   464.88815859,   857.68525696,   857.93997459],
       [  218.69156362,   520.85410625,   273.05677065,     0.        ,
          462.10929443,   430.99071916,   718.0250692 ,   590.427811  ],
       [  399.68612685,   385.1700923 ,   629.16532009,   462.10929443,
            0.        ,   886.01580121,   258.31182706,   465.72524089],
       [  533.56630328,   825.10847772,   464.88815859,   430.99071916,
          886.01580121,     0.        ,  1144.09309062,   864.76123872],
       [  649.85690733,   545.50985326,   857.68525696,   718.0250692 ,
          258.31182706,  1144.09309062,     0.        ,   

In [221]:
W3 = _Kernel(D3, function='gaussian', truncate=False)

In [224]:
W3.dmat

array([[    0.        ,   313.40867888,   491.3023509 ,   218.69156362,
          399.68612685,   533.56630328,   649.85690733,   376.04919891],
       [  313.40867888,     0.        ,   784.01594372,   520.85410625,
          385.1700923 ,   825.10847772,   545.50985326,    85.27602242],
       [  491.3023509 ,   784.01594372,     0.        ,   273.05677065,
          629.16532009,   464.88815859,   857.68525696,   857.93997459],
       [  218.69156362,   520.85410625,   273.05677065,     0.        ,
          462.10929443,   430.99071916,   718.0250692 ,   590.427811  ],
       [  399.68612685,   385.1700923 ,   629.16532009,   462.10929443,
            0.        ,   886.01580121,   258.31182706,   465.72524089],
       [  533.56630328,   825.10847772,   464.88815859,   430.99071916,
          886.01580121,     0.        ,  1144.09309062,   864.76123872],
       [  649.85690733,   545.50985326,   857.68525696,   718.0250692 ,
          258.31182706,  1144.09309062,     0.        ,   

In [225]:
34-8

26

In [227]:
np.unique(g)

array([    0.        ,   218.69156362,   273.05677065,   313.40867888,
         385.1700923 ,   399.68612685,   462.10929443,   491.3023509 ,
         520.85410625,   607.21083653,   629.16532009,   784.01594372,
         864.76123872,  1144.09309062])

In [230]:
v = sp.cdist(D1, D2)

In [243]:
n = []
for each in v.flatten(): 
    if each in c: 
        n.append(each)
        
n = np.array(n)
n = n.reshape((5,3))
n

array([[ 533.56630328,  649.85690733,  376.04919891],
       [ 825.10847772,  545.50985326,   85.27602242],
       [ 464.88815859,  857.68525696,  857.93997459],
       [ 430.99071916,  718.0250692 ,  590.427811  ],
       [ 886.01580121,  258.31182706,  465.72524089]])

In [237]:
n.reshape((3,5))

array([[ 533.56630328,  649.85690733,  376.04919891,  825.10847772,
         545.50985326],
       [  85.27602242,  464.88815859,  857.68525696,  857.93997459,
         430.99071916],
       [ 718.0250692 ,  590.427811  ,  886.01580121,  258.31182706,
         465.72524089]])

In [245]:
sp.cdist(D1,D2)

array([[ 533.56630328,  649.85690733,  376.04919891],
       [ 825.10847772,  545.50985326,   85.27602242],
       [ 464.88815859,  857.68525696,  857.93997459],
       [ 430.99071916,  718.0250692 ,  590.427811  ],
       [ 886.01580121,  258.31182706,  465.72524089]])

In [272]:
W3.dmat[5:,:-3].T

array([[ 533.56630328,  649.85690733,  376.04919891],
       [ 825.10847772,  545.50985326,   85.27602242],
       [ 464.88815859,  857.68525696,  857.93997459],
       [ 430.99071916,  718.0250692 ,  590.427811  ],
       [ 886.01580121,  258.31182706,  465.72524089]])

In [273]:
W3.full()[0][5:,:-3].T

AttributeError: '_Kernel' object has no attribute 'full'

In [279]:
W3.kernel[5:,:-3].T

array([[ 0.3578336 ,  0.33950844,  0.37796401],
       [ 0.30758741,  0.3560763 ,  0.39783564],
       [ 0.36733036,  0.30121336,  0.30116308],
       [ 0.37161625,  0.32762844,  0.34920341],
       [ 0.29558272,  0.38890253,  0.36722107]])

In [290]:
W3 = kn(D3, function='gaussian', truncate=False)
W3.full()[0][5:,:-3].T

array([[ 0.24726767,  0.19622043,  0.31457187],
       [ 0.12709312,  0.24197075,  0.39409745],
       [ 0.27746287,  0.11590961,  0.11582453],
       [ 0.29198776,  0.1677652 ,  0.22209064],
       [ 0.10667727,  0.356632  ,  0.27709994]])

In [288]:
W3 = _Kernel(D3, function='gaussian', truncate=False, k=2)
W3.kernel[5:,:-3].T

In [289]:
W3.kernel[5:,:-3].T

array([[ 0.24726767,  0.19622043,  0.31457187],
       [ 0.12709312,  0.24197075,  0.39409745],
       [ 0.27746287,  0.11590961,  0.11582453],
       [ 0.29198776,  0.1677652 ,  0.22209064],
       [ 0.10667727,  0.356632  ,  0.27709994]])