In [9]:
import numpy as np
import pysal as ps
from pysal.weights.Distance import Kernel
import sys
sys.path.append('/Users/toshan/dev/pysal/pysal/weights')
from Distance import Kernel as kn
from util import full2W as f2w

In [2]:
n = 5 #number of observations
m = 3 #number of calibration points

In [17]:
x = np.random.randint(1,1000, n)
y = np.random.randint(1,1000, n)
D1 = zip(x,y)
W1 = kn(D1)

In [18]:
x = np.random.randint(1,1000, m)
y = np.random.randint(1,1000, m)
D2 = zip(x,y)
W2 = kn(D2)

In [39]:
D3 = np.vstack([D1,D2])
W3 = Kernel(D3, function='gaussian')
W3 = kn(D3, function='gaussian', truncate=False)

W3.full()[0]

array([[ 0.39894228,  0.1009935 ,  0.05619733,  0.04896355,  0.32650695,
         0.37879836,  0.31411809,  0.1073076 ],
       [ 0.1009935 ,  0.39894228,  0.36195557,  0.36626279,  0.07720723,
         0.11754135,  0.03669346,  0.33721825],
       [ 0.05619733,  0.36195557,  0.39894228,  0.39108403,  0.0345001 ,
         0.06151089,  0.02103471,  0.24420603],
       [ 0.04896355,  0.36626279,  0.39108403,  0.39894228,  0.0335092 ,
         0.05713611,  0.01604658,  0.26976648],
       [ 0.32650695,  0.07720723,  0.0345001 ,  0.0335092 ,  0.39894228,
         0.37224696,  0.18985479,  0.11774827],
       [ 0.37879836,  0.11754135,  0.06151089,  0.05713611,  0.37224696,
         0.39894228,  0.24197075,  0.14519262],
       [ 0.31411809,  0.03669346,  0.02103471,  0.01604658,  0.18985479,
         0.24197075,  0.39894228,  0.03119528],
       [ 0.1073076 ,  0.33721825,  0.24420603,  0.26976648,  0.11774827,
         0.14519262,  0.03119528,  0.39894228]])

In [40]:

coord_ids = np.arange(n)
points_ids = np.arange(n, n+m)
all_ids = np.arange(n+m)
dists = np.zeros((m,n))


for i in all_ids:
    if i in points_ids:
        for j in coord_ids:
            if j in W3[j].keys():
                if i >= n:
                    print 'a'
                    dists[i-n][j] = W3.full()[0][i][j]
                elif j >= m:
                    print 'b'
                    dists[i][j-m] = W3.full()[0][i][j]
                elif (i >= n) & (j >= m):
                    print 'c'
                    dists[i-n][j-m] = W3.full()[0][i][j]
                else:
                    print 'd'
                    dists[i][j] = W3.full()[0][i][j]



a
a
a
a
a
a
a
a
a
a
a
a
a
a
a


In [41]:
dists

array([[ 0.37879836,  0.11754135,  0.06151089,  0.05713611,  0.37224696],
       [ 0.31411809,  0.03669346,  0.02103471,  0.01604658,  0.18985479],
       [ 0.1073076 ,  0.33721825,  0.24420603,  0.26976648,  0.11774827]])

In [22]:
w = f2w(dists)
w.full()[0]

ValueError: 3 is not in list

In [23]:
new_neighbs = {}
new_weights = {}
for each in W2.neighbors:
    three = set(W3.neighbors[each])
    two = set(W2.neighbors[each])
    new_neighbs[each] = list(three.difference(two))
    new_weights[each] = {}
    for weight in new_neighbs[each]:
        new_weights[each][weight] = W3[each][weight]

In [24]:
coord_ids = W1.id_order
points_ids = W2.id_order
all_ids = W3.id_order
dists = np.zeros((2,3))

'''
for ids in all_ids:
    if ids in points_ids:
        _all = set(W3.neighbors[ids])
        points = set(W2.neighbors[ids])
        new_neighbs[ids] = list(_all.difference(points))
        new_weights[ids] = {}
        for weight in new_neighbs[ids]:
            new_weights[ids][weight] = W3[ids][weight]

    else:
        new_weights[ids] = {}
'''       


'\nfor ids in all_ids:\n    if ids in points_ids:\n        _all = set(W3.neighbors[ids])\n        points = set(W2.neighbors[ids])\n        new_neighbs[ids] = list(_all.difference(points))\n        new_weights[ids] = {}\n        for weight in new_neighbs[ids]:\n            new_weights[ids][weight] = W3[ids][weight]\n\n    else:\n        new_weights[ids] = {}\n'

In [10]:
n = 3 #number of observations
m = 2 #number of 
for i in all_ids:
    if i in points_ids:
        for j in coord_ids:
            if j in W3[j].keys():
                print i,j
                if i >= n:
                    print 'a'
                    dists[i-n][j] = W3.full()[0][i][j]
                elif j >= m:
                    print 'b'
                    dists[i][j-m] = W3.full()[0][i][j]
                elif (i >= n) & (j >= m):
                    print 'c'
                    dists[i-n][j-m] = W3.full()[0][i][j]
                else:
                    print 'd'
                    dists[i][j] = W3.full()[0][i][j]


3 0
a
3 1
a
3 2
a
4 0
a
4 1
a
4 2
a
5 0
a
5 1
a
5 2
a
6 0
a
6 1
a
6 2
a
7 0
a
7 1
a
7 2
a


In [11]:
dists

array([[ 0.        ,  0.45118883,  0.85404129],
       [ 0.27754126,  0.40233088,  0.20596816],
       [ 0.        ,  0.37941649,  0.6032733 ],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.35446728,  0.73305802,  0.50022967]])

In [16]:
points_ids

[0, 1]

In [25]:
W4 = ps.W(new_neighbs, new_weights)

In [26]:
W4.neighbors

{0: [3, 4, 5, 6, 7], 1: [3, 4, 5, 6, 7], 2: [3, 4, 5, 6, 7]}

In [27]:
W4.weights

{0: {3: -1.0482874068379293,
  4: 0.36696681575222334,
  5: 0.678090925231672,
  6: 0.308555499289517,
  7: -0.620566108018012},
 1: {3: 0.5865615659374835,
  4: -0.8123595700046831,
  5: -0.5633467635255329,
  6: -1.1845906645769202,
  7: 0.42019589403802593},
 2: {3: 0.8005291815217084,
  4: -1.212624893235362,
  5: -0.9337024333901489,
  6: -1.4259607135415542,
  7: 0.009238162970930053}}

In [28]:
W4.id_order

[0, 1, 2]

In [29]:
W4.full()[0]

ValueError: 3 is not in list

In [244]:
W4.

{1: 1}

In [35]:
np.arange(5,6)

array([5])