In [23]:
import numpy as np
import pysal as ps
from pysal.weights.Distance import Kernel

In [30]:
n = 3 #number of observations
m = 5 #number of calibration points

In [31]:
x = np.random.randint(1,100, n)
y = np.random.randint(1,100, n)
D1 = zip(x,y)

In [32]:
x = np.random.randint(1,100, m)
y = np.random.randint(1,100, m)
D2 = zip(x,y)

In [33]:
D3 = np.vstack([D1,D2])
W3 = Kernel(D3)



In [34]:

coord_ids = np.arange(n)
points_ids = np.arange(n, n+m)
all_ids = np.arange(n+m)
dists = np.zeros((m,n))


for i in all_ids:
    if i in points_ids:
        for j in coord_ids:
            if j in W3[j].keys():
                if i >= n:
                    print 'a'
                    dists[i-n][j] = W3.full()[0][i][j]
                elif j >= m:
                    print 'b'
                    dists[i][j-m] = W3.full()[0][i][j]
                elif (i >= n) & (j >= m):
                    print 'c'
                    dists[i-n][j-m] = W3.full()[0][i][j]
                else:
                    print 'd'
                    dists[i][j] = W3.full()[0][i][j]



a
a
a
a
a
a
a
a
a
a
a
a
a
a
a


In [35]:
dists

array([[  0.00000000e+00,   0.00000000e+00,   9.99999901e-08],
       [  1.94048304e-01,   4.25327793e-01,   6.86243093e-01],
       [  4.87226734e-01,   0.00000000e+00,   3.05954234e-01],
       [  0.00000000e+00,   7.67802507e-02,   3.76184399e-01],
       [  1.14222216e-01,   3.32212480e-01,   2.31182026e-01]])

In [22]:
new_neighbs = {}
new_weights = {}
for each in W2.neighbors:
    three = set(W3.neighbors[each])
    two = set(W2.neighbors[each])
    new_neighbs[each] = list(three.difference(two))
    new_weights[each] = {}
    for weight in new_neighbs[each]:
        new_weights[each][weight] = W3[each][weight]

In [23]:
coord_ids = W1.id_order
points_ids = W2.id_order
all_ids = W3.id_order
dists = np.zeros((2,3))

'''
for ids in all_ids:
    if ids in points_ids:
        _all = set(W3.neighbors[ids])
        points = set(W2.neighbors[ids])
        new_neighbs[ids] = list(_all.difference(points))
        new_weights[ids] = {}
        for weight in new_neighbs[ids]:
            new_weights[ids][weight] = W3[ids][weight]

    else:
        new_weights[ids] = {}
'''       


'\nfor ids in all_ids:\n    if ids in points_ids:\n        _all = set(W3.neighbors[ids])\n        points = set(W2.neighbors[ids])\n        new_neighbs[ids] = list(_all.difference(points))\n        new_weights[ids] = {}\n        for weight in new_neighbs[ids]:\n            new_weights[ids][weight] = W3[ids][weight]\n\n    else:\n        new_weights[ids] = {}\n'

In [26]:
n = 3 #number of observations
m = 2 #number of 
for i in all_ids:
    if i in points_ids:
        for j in coord_ids:
            if j in W3[j].keys():
                print i,j
                if i >= n:
                    print 'a'
                    dists[i-n][j] = W3.full()[0][i][j]
                elif j >= m:
                    print 'b'
                    dists[i][j-m] = W3.full()[0][i][j]
                elif (i >= n) & (j >= m):
                    print 'c'
                    dists[i-n][j-m] = W3.full()[0][i][j]
                else:
                    print 'd'
                    dists[i][j] = W3.full()[0][i][j]


3 0
a
3 1
a
3 2
a
4 0
a
4 1
a
4 2
a


In [27]:
dists

array([[ 0.50000005,  0.09861227,  0.25000007],
       [ 0.        ,  0.09861227,  0.        ]])

In [16]:
points_ids

[0, 1]

In [234]:
W4 = ps.W(new_neighbs, new_weights)

Island ids:  [0, 1, 2]


In [235]:
W4.neighbors

{0: [], 1: [], 2: [], 3: [0, 1, 2], 4: [1]}

In [236]:
W4.weights

{0: {},
 1: {},
 2: {},
 3: {0: 0.500000049999995, 1: 0.09861227127277583, 2: 0.25000007499999266},
 4: {1: 0.09861227127277583}}

In [237]:
W4.id_order

[0, 1, 2, 3, 4]

In [239]:
W4.full()[0]

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  2.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.]])

In [244]:
W4.

{1: 1}

In [35]:
np.arange(5,6)

array([5])