In [1]:
import sys
import numpy as np
import pandas as pd
import pysal as ps
sys.path.append('/Users/toshan/Dropbox/GWR/PyGWRJing/PyGWR/')
from M_FBGWR_May2016 import FBGWR
import scipy
from scipy.spatial.kdtree import KDTree
from pysal.weights import W

In [2]:
path = ps.examples.get_path('GData_utm.csv')
shp = pd.read_csv(path)

In [3]:
# Prep data into design matrix and coordinates

#Dependent variable
y = shp.PctBach.reshape((-1,1))

#Design matrix - covariates - intercept added automatically
pov = shp.PctPov.reshape((-1,1))
rural = shp.PctRural.reshape((-1,1))
blk = shp.PctBlack.reshape((-1,1))
X = np.hstack([pov, rural, blk])
labels = ['Intercept', 'PctPov', 'PctRural', 'PctBlack']

#Coordinates for calibration points
u = shp.X
v = shp.Y
coords = zip(u,v)

coords_dict = {}
for i, x in enumerate(coords):
        coords_dict[i] = x

In [4]:
from pysal.contrib.gwr.sel_bw import Sel_BW
from pysal.contrib.gwr.gwr import GWR

In [7]:
sel = Sel_BW(coords, y, X, [], kernel='bisquare')
results = sel.search()


//anaconda/envs/fbgwr/lib/python2.7/site-packages/PySAL-1.11.2-py2.7.egg/pysal/contrib/gwr/kernels.py:85: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  dmat = np.sort(self.dmat)[:,:self.k]


KeyboardInterrupt: 

In [6]:
results = FBGWR(y, X, coords_dict, tolFB=.005)

46 159
1000000.0 0
[[  6.88047392]
 [  1.79871176]
 [  5.01657236]
 [  3.72792665]
 [ 11.54923093]
 [  5.27868147]
 [  7.79330774]
 [ -0.53398084]
 [  2.12492367]
 [  5.48246364]
 [  7.94046992]
 [  6.72599982]
 [  7.64917375]
 [  3.97994212]
 [ 13.18328154]
 [ 21.13996028]
 [ 11.3682929 ]
 [ -2.50923719]
 [  1.87902577]
 [  9.97752117]
 [ 10.79326493]
 [  3.55402491]
 [  4.77128146]
 [  1.91128326]
 [ 13.54544005]
 [ 10.74941172]
 [ -2.74065052]
 [ 13.44996402]
 [ 40.83572884]
 [  1.06165212]
 [  7.34881873]
 [  1.40413171]
 [ 27.85355546]
 [  7.42913317]
 [  7.37004606]
 [ 24.83629964]
 [  2.29982863]
 [  1.72141228]
 [ -4.2815012 ]
 [  4.39921596]
 [  1.48554358]
 [  3.85923812]
 [  7.49736324]
 [ 20.76952688]
 [  3.97616236]
 [  0.42205162]
 [ 10.60667748]
 [  7.87625186]
 [  3.1318151 ]
 [  2.84915691]
 [ 10.41969604]
 [ 14.22429697]
 [ 10.55453463]
 [  9.44327485]
 [  2.29984231]
 [ 22.01076619]
 [  5.2480904 ]
 [ 11.85247262]
 [ 10.00744582]
 [ 12.7158585 ]
 [  2.12647471]
 [  3

In [9]:
results.opt_band

AttributeError: 'numpy.float64' object has no attribute 'opt_band'

In [5]:
data = pd.read_csv('/Users/toshan/Dropbox/Articles/MC_Sims/data/variables/0_0.csv')
X = np.hstack([data['X1'].values.reshape((-1,1)), data['X2'].values.reshape((-1,1))])
y = data['Y'].values.reshape((-1,1))
coords = list(zip(data['Xcoord'], data['Ycoord']))

In [7]:
%%time
sel = Sel_BW(coords[:500], y[:500], X[:500], [], kernel='bisquare')
results = sel.search()

//anaconda/envs/fbgwr/lib/python2.7/site-packages/PySAL-1.11.2-py2.7.egg/pysal/contrib/gwr/kernels.py:85: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  dmat = np.sort(self.dmat)[:,:self.k]


KeyboardInterrupt: 

In [8]:
%%time
sel = Sel_BW(coords[:1000], y[:1000], X[:1000], [], kernel='bisquare')
results = sel.search()

KeyboardInterrupt: 

In [ ]:
%%time
sel = Sel_BW(coords, y, X, [], kernel='bisquare')
results = sel.search()

//anaconda/envs/fbgwr/lib/python2.7/site-packages/PySAL-1.11.2-py2.7.egg/pysal/contrib/gwr/kernels.py:85: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  dmat = np.sort(self.dmat)[:,:self.k]


In [6]:
from scipy.spatial import kdtree
from pysal.weights import Kernel

In [11]:
mod = GWR(coords, y, X, bw=1000)

In [1]:
%time w = Kernel(coords, fixed=False, k=1000, function='bisquare', diagonal=True, truncate=True)


NameError: name 'Kernel' is not defined

In [8]:
%time w = Kernel(coords, fixed=False, k=200, function='bisquare', diagonal=True, truncate=True)



CPU times: user 14.9 s, sys: 14.1 ms, total: 14.9 s
Wall time: 14.9 s


In [9]:
%time w = Kernel(coords, fixed=False, k=300, function='bisquare', diagonal=True, truncate=True)



CPU times: user 31.9 s, sys: 28.8 ms, total: 32 s
Wall time: 32 s


In [49]:
%time w = Kernel(coords, fixed=True, bandwidth=5, function='bisquare', diagonal=True, truncate=True)



CPU times: user 2.5 s, sys: 12.2 ms, total: 2.52 s
Wall time: 2.51 s


In [50]:
%time w = Kernel(coords, fixed=True, bandwidth=10, function='bisquare', diagonal=True, truncate=True)



CPU times: user 26.5 s, sys: 37.2 ms, total: 26.6 s
Wall time: 26.6 s


In [51]:
%time w = Kernel(coords, fixed=True, bandwidth=15, function='bisquare', diagonal=True, truncate=True)




CPU times: user 1min 53s, sys: 99.8 ms, total: 1min 53s
Wall time: 1min 53s


In [13]:
%time tree.query(coords, k=100)

CPU times: user 3.17 s, sys: 12.8 ms, total: 3.19 s
Wall time: 3.19 s


(array([[  0.        ,   1.        ,   1.        , ...,  10.44030651,
          10.63014581,  10.63014581],
        [  0.        ,   1.        ,   1.        , ...,  10.        ,
          10.        ,  10.        ],
        [  0.        ,   1.        ,   1.        , ...,   9.21954446,
           9.21954446,   9.43398113],
        ..., 
        [  0.        ,   1.        ,   1.        , ...,   9.21954446,
           9.21954446,   9.43398113],
        [  0.        ,   1.        ,   1.        , ...,  10.        ,
          10.        ,  10.        ],
        [  0.        ,   1.        ,   1.        , ...,  10.44030651,
          10.63014581,  10.63014581]]),
 array([[   0,    1,   50, ...,  503,  358,  407],
        [   1,    0,    2, ...,  309,  407,  501],
        [   2,    1,    3, ...,  450,  454,  407],
        ..., 
        [2497, 2447, 2496, ..., 2190, 2388, 2239],
        [2498, 2448, 2497, ..., 2092, 2190, 2488],
        [2499, 2449, 2498, ..., 2339, 2092, 2141]]))

In [16]:
%time tree.query(coords, k=200)

CPU times: user 5.58 s, sys: 16.1 ms, total: 5.6 s
Wall time: 5.61 s


(array([[  0.        ,   1.        ,   1.        , ...,  15.23154621,
          15.23154621,  15.26433752],
        [  0.        ,   1.        ,   1.        , ...,  14.56021978,
          14.76482306,  14.76482306],
        [  0.        ,   1.        ,   1.        , ...,  14.03566885,
          14.03566885,  14.14213562],
        ..., 
        [  0.        ,   1.        ,   1.        , ...,  14.03566885,
          14.03566885,  14.14213562],
        [  0.        ,   1.        ,   1.        , ...,  14.56021978,
          14.76482306,  14.76482306],
        [  0.        ,   1.        ,   1.        , ...,  15.23154621,
          15.23154621,  15.26433752]]),
 array([[   0,    1,   50, ...,  314,  706,  658],
        [   1,    0,    2, ...,  705,  364,  658],
        [   2,    1,    3, ...,  701,  703,  704],
        ..., 
        [2497, 2447, 2496, ..., 1798, 2433, 1987],
        [2498, 2448, 2497, ..., 2284, 1841, 2135],
        [2499, 2449, 2498, ..., 1793, 2185, 2086]]))

In [17]:
%time tree.query(coords, k=300)

CPU times: user 8.2 s, sys: 31.7 ms, total: 8.24 s
Wall time: 8.26 s


(array([[  0.        ,   1.        ,   1.        , ...,  18.86796226,
          18.97366596,  18.97366596],
        [  0.        ,   1.        ,   1.        , ...,  18.11077028,
          18.24828759,  18.24828759],
        [  0.        ,   1.        ,   1.        , ...,  17.69180601,
          17.69180601,  17.72004515],
        ..., 
        [  0.        ,   1.        ,   1.        , ...,  17.69180601,
          17.69180601,  17.72004515],
        [  0.        ,   1.        ,   1.        , ...,  18.11077028,
          18.24828759,  18.24828759],
        [  0.        ,   1.        ,   1.        , ...,  18.86796226,
          18.97366596,  18.97366596]]),
 array([[   0,    1,   50, ...,  810,  318,  906],
        [   1,    0,    2, ...,  903,  169,  904],
        [   2,    1,    3, ...,  615,  664,  857],
        ..., 
        [2497, 2447, 2496, ..., 1835, 1884, 2230],
        [2498, 2448, 2497, ..., 2380, 1595, 2330],
        [2499, 2449, 2498, ..., 1983, 1593, 2181]]))

In [49]:
%%time
bandwidth = np.ones((50, 1))*50
kdtq = tree.query_ball_point
neighbors = [kdtq(coords[i], r=bwi[0]) for i,
            bwi in enumerate(bandwidth)]


CPU times: user 203 ms, sys: 2.37 ms, total: 205 ms
Wall time: 204 ms


In [50]:
%%time

bw = bandwidth

kdtq = tree.query
z = []
for i, nids in enumerate(neighbors):
    di, ni = kdtq(coords[i], k=len(nids))
    if not isinstance(di, np.ndarray):
        di = np.asarray([di] * len(nids))
        ni = np.asarray([ni] * len(nids))
    zi = np.array([dict(zip(ni, di))[nid] for nid in nids]) / bw[i]
    z.append(zi)
zs = z

kernel = [(1-(zi)**2)**2 for zi in zs]


CPU times: user 39.7 s, sys: 104 ms, total: 39.8 s
Wall time: 39.7 s


In [51]:
np.array(zs).shape

(50,)

In [48]:
np.sqrt(5000)

70.710678118654755

In [179]:
class Kernel(W):
    """
    Spatial weights based on kernel functions.

    Parameters
    ----------

    data        : array
                  (n,k) or KDTree where KDtree.data is array (n,k)
                  n observations on k characteristics used to measure
                  distances between the n objects
    bandwidth   : float
                  or array-like (optional)
                  the bandwidth :math:`h_i` for the kernel.
    fixed       : binary
                  If true then :math:`h_i=h \\forall i`. If false then
                  bandwidth is adaptive across observations.
    k           : int
                  the number of nearest neighbors to use for determining
                  bandwidth. For fixed bandwidth, :math:`h_i=max(dknn) \\forall i`
                  where :math:`dknn` is a vector of k-nearest neighbor
                  distances (the distance to the kth nearest neighbor for each
                  observation).  For adaptive bandwidths, :math:`h_i=dknn_i`
    diagonal    : boolean
                  If true, set diagonal weights = 1.0, if false (default),
                  diagonals weights are set to value according to kernel
                  function.
    function    : {'triangular','uniform','quadratic','quartic','gaussian'}
                  kernel function defined as follows with

                  .. math::

                      z_{i,j} = d_{i,j}/h_i

                  triangular

                  .. math::

                      K(z) = (1 - |z|) \ if |z| \le 1

                  uniform

                  .. math::

                      K(z) = 1/2 \ if |z| \le 1

                  quadratic

                  .. math::

                      K(z) = (3/4)(1-z^2) \ if |z| \le 1

                  quartic

                  .. math::

                      K(z) = (15/16)(1-z^2)^2 \ if |z| \le 1

                  gaussian

                  .. math::

                      K(z) = (2\pi)^{(-1/2)} exp(-z^2 / 2)

    eps         : float
                  adjustment to ensure knn distance range is closed on the
                  knnth observations
    truncate    : boolean
                  True for forced 0 values after bandwidth, False for weighting
                  all points

    Attributes
    ----------
    weights : dict
              Dictionary keyed by id with a list of weights for each neighbor

    neighbors : dict
                of lists of neighbors keyed by observation id

    bandwidth : array
                array of bandwidths

    Examples
    --------

    >>> points=[(10, 10), (20, 10), (40, 10), (15, 20), (30, 20), (30, 30)]
    >>> kw=Kernel(points)
    >>> kw.weights[0]
    [1.0, 0.500000049999995, 0.4409830615267465]
    >>> kw.neighbors[0]
    [0, 1, 3]
    >>> kw.bandwidth
    array([[ 20.000002],
           [ 20.000002],
           [ 20.000002],
           [ 20.000002],
           [ 20.000002],
           [ 20.000002]])
    >>> kw15=Kernel(points,bandwidth=15.0)
    >>> kw15[0]
    {0: 1.0, 1: 0.33333333333333337, 3: 0.2546440075000701}
    >>> kw15.neighbors[0]
    [0, 1, 3]
    >>> kw15.bandwidth
    array([[ 15.],
           [ 15.],
           [ 15.],
           [ 15.],
           [ 15.],
           [ 15.]])

    Adaptive bandwidths user specified

    >>> bw=[25.0,15.0,25.0,16.0,14.5,25.0]
    >>> kwa=Kernel(points,bandwidth=bw)
    >>> kwa.weights[0]
    [1.0, 0.6, 0.552786404500042, 0.10557280900008403]
    >>> kwa.neighbors[0]
    [0, 1, 3, 4]
    >>> kwa.bandwidth
    array([[ 25. ],
           [ 15. ],
           [ 25. ],
           [ 16. ],
           [ 14.5],
           [ 25. ]])

    Endogenous adaptive bandwidths

    >>> kwea=Kernel(points,fixed=False)
    >>> kwea.weights[0]
    [1.0, 0.10557289844279438, 9.99999900663795e-08]
    >>> kwea.neighbors[0]
    [0, 1, 3]
    >>> kwea.bandwidth
    array([[ 11.18034101],
           [ 11.18034101],
           [ 20.000002  ],
           [ 11.18034101],
           [ 14.14213704],
           [ 18.02775818]])

    Endogenous adaptive bandwidths with Gaussian kernel

    >>> kweag=Kernel(points,fixed=False,function='gaussian')
    >>> kweag.weights[0]
    [0.3989422804014327, 0.2674190291577696, 0.2419707487162134]
    >>> kweag.bandwidth
    array([[ 11.18034101],
           [ 11.18034101],
           [ 20.000002  ],
           [ 11.18034101],
           [ 14.14213704],
           [ 18.02775818]])

    Diagonals to 1.0

    >>> kq = Kernel(points,function='gaussian')
    >>> kq.weights
    {0: [0.3989422804014327, 0.35206533556593145, 0.3412334260702758], 1: [0.35206533556593145, 0.3989422804014327, 0.2419707487162134, 0.3412334260702758, 0.31069657591175387], 2: [0.2419707487162134, 0.3989422804014327, 0.31069657591175387], 3: [0.3412334260702758, 0.3412334260702758, 0.3989422804014327, 0.3011374490937829, 0.26575287272131043], 4: [0.31069657591175387, 0.31069657591175387, 0.3011374490937829, 0.3989422804014327, 0.35206533556593145], 5: [0.26575287272131043, 0.35206533556593145, 0.3989422804014327]}
    >>> kqd = Kernel(points, function='gaussian', diagonal=True)
    >>> kqd.weights
    {0: [1.0, 0.35206533556593145, 0.3412334260702758], 1: [0.35206533556593145, 1.0, 0.2419707487162134, 0.3412334260702758, 0.31069657591175387], 2: [0.2419707487162134, 1.0, 0.31069657591175387], 3: [0.3412334260702758, 0.3412334260702758, 1.0, 0.3011374490937829, 0.26575287272131043], 4: [0.31069657591175387, 0.31069657591175387, 0.3011374490937829, 1.0, 0.35206533556593145], 5: [0.26575287272131043, 0.35206533556593145, 1.0]}

    """
    def __init__(self, data, bandwidth=None, fixed=True, k=2,
                 function='triangular', eps=1.0000001, ids=None,
                 diagonal=False, truncate=True): #Added truncate flag
        if issubclass(type(data), scipy.spatial.KDTree):
            self.kdt = data
            self.data = self.kdt.data
            data = self.data
        else:
            self.data = data
            self.kdt = KDTree(self.data)
        self.k = k + 1
        self.function = function.lower()
        self.fixed = fixed
        self.eps = eps
        self.trunc = truncate
        if bandwidth:
            try:
                bandwidth = np.array(bandwidth)
                bandwidth.shape = (len(bandwidth), 1)
            except:
                bandwidth = np.ones((len(data), 1), 'float') * bandwidth
            self.bandwidth = bandwidth
        else:
            self._set_bw()
        self._eval_kernel()

        neighbors, weights = self._k_to_W(ids)
        if diagonal:
            for i in neighbors:
                weights[i][neighbors[i].index(i)] = 1.0
        W.__init__(self, neighbors, weights, ids)

    def _k_to_W(self, ids=None):
        allneighbors = {}
        weights = {}
        if ids:
        
            ids = np.array(ids)
        else:
            ids = np.arange(len(self.data))
        for i, neighbors in enumerate(self.kernel):
            if len(self.neigh[i]) == 0:
                allneighbors[ids[i]] = []
                weights[ids[i]] = []
            else:
                allneighbors[ids[i]] = list(ids[self.neigh[i]])
                weights[ids[i]] = self.kernel[i].tolist()
        return allneighbors, weights

    def _set_bw(self):
        dmat, neigh = self.kdt.query(self.data, k=self.k)
        if self.fixed:
            # use max knn distance as bandwidth
            bandwidth = dmat.max() * self.eps
            n = len(dmat)
            self.bandwidth = np.ones((n, 1), 'float') * bandwidth
        else:
            # use local max knn distance
            self.bandwidth = dmat.max(axis=1) * self.eps
            self.bandwidth.shape = (self.bandwidth.size, 1)
            # identify knn neighbors for each point
            nnq = self.kdt.query(self.data, k=self.k)
            self.neigh = nnq[1]

    def _eval_kernel(self):
        # get points within bandwidth distance of each point
        if self.trunc:#Check for truncate flag here
            if not hasattr(self, 'neigh'):
                kdtq = self.kdt.query_ball_point
                neighbors = [kdtq(self.data[i], r=bwi[0]) for i,
                            bwi in enumerate(self.bandwidth)]
                self.neigh = neighbors
        else:
            n = len(self.data)
            self.neigh = [range(n) for each in range(n)]
        # get distances for neighbors
        bw = self.bandwidth

        kdtq = self.kdt.query
        z = []
        for i, nids in enumerate(self.neigh):
            di, ni = kdtq(self.data[i], k=len(nids))
            if not isinstance(di, np.ndarray):
                di = np.asarray([di] * len(nids))
                ni = np.asarray([ni] * len(nids))
            zi = np.array([dict(zip(ni, di))[nid] for nid in nids]) / bw[i]
            z.append(zi)
        zs = z
        print (1-(zs[0][1])**2)**2
        print np.array(zs).shape
        # functions follow Anselin and Rey (2010) table 5.4
        if self.function == 'triangular':
            self.kernel = [1 - zi for zi in zs]
        elif self.function == 'uniform':
            self.kernel = [np.ones(zi.shape) * 0.5 for zi in zs]
        elif self.function == 'quadratic':
            self.kernel = [(3. / 4) * (1 - zi ** 2) for zi in zs]
        elif self.function == 'quartic':
            self.kernel = [(15. / 16) * (1 - zi ** 2) ** 2 for zi in zs]
        elif self.function == 'gaussian':
            c = np.pi * 2
            c = c ** (-0.5)
            self.kernel = [c * np.exp(-(zi ** 2) / 2.) for zi in zs]
        elif self.function == 'gwr_gaussian':
            self.kernel = [ np.exp(-0.5*(zi)**2) for zi in zs]
        elif self.function == 'bisquare':
            self.kernel = [(1-(zi)**2)**2 for zi in zs]
        elif self.function =='exponential':
            self.kernel = [np.exp(-zi) for zi in zs]
        else:
            print('Unsupported kernel function', self.function)




In [5]:
from scipy.spatial.distance import cdist

class GWRKernel(object):
    """

    """
    def __init__(self, data, bandwidth=None, fixed=True, k=None,
                 function='triangular', eps=1.0000001, ids=None, truncate=True): #Added truncate flag
        if issubclass(type(data), scipy.spatial.KDTree):
            self.kdt = data
            self.data = self.kdt.data
            data = self.data
        else:
            self.data = data
            self.kdt = KDTree(self.data)
        if k is not None:
            self.k = k + 1
        else:
            self.k = k
        self.dmat = cdist(self.data, self.data)
        self.function = function.lower()
        self.fixed = fixed
        self.eps = eps
        self.trunc = truncate
        if bandwidth:
            try:
                bandwidth = np.array(bandwidth)
                bandwidth.shape = (len(bandwidth), 1)
            except:
                bandwidth = np.ones((len(data), 1), 'float') * bandwidth
            self.bandwidth = bandwidth
        else:
            self._set_bw()
        self.kernel = self._kernel_funcs(self.dmat/self.bandwidth)
        
        if self.trunc:
            mask = np.repeat(self.bandwidth, len(self.bandwidth), axis=1)
            kernel_mask = self._kernel_funcs(1.0/mask)
            self.kernel[(self.dmat >= mask)] = 0



    def _set_bw(self):
        if self.k is not None:
            dmat = np.sort(self.dmat)[:,:self.k]
        else:
            dmat = self.dmat
        if self.fixed:
            # use max knn distance as bandwidth
            bandwidth = dmat.max() * self.eps
            n = len(self.data)
            self.bandwidth = np.ones((n, 1), 'float') * bandwidth
        else:
            # use local max knn distance
            self.bandwidth = dmat.max(axis=1) * self.eps
            self.bandwidth.shape = (self.bandwidth.size, 1)
            

    def _kernel_funcs(self, zs):
        # functions follow Anselin and Rey (2010) table 5.4
        if self.function == 'triangular':
            return 1 - zs 
        elif self.function == 'uniform':
            return np.ones(zi.shape) * 0.5 
        elif self.function == 'quadratic':
            return (3. / 4) * (1 - zs ** 2) 
        elif self.function == 'quartic':
            return (15. / 16) * (1 - zs ** 2) ** 2 
        elif self.function == 'gaussian':
            c = np.pi * 2
            c = c ** (-0.5)
            return c * np.exp(-(zs ** 2) / 2.)
        elif self.function == 'gwr_gaussian':
            return np.exp(-0.5*(zs)**2)
        elif self.function == 'bisquare':
            print (1-(zs[0][1])**2)**2
            return (1-(zs)**2)**2
        elif self.function =='exponential':
            return np.exp(-zs)
        else:
            print('Unsupported kernel function', self.function)

In [6]:
%time gwrw = GWRKernel(coords, fixed=False, function='bisquare', truncate=True, k=100)

0.982832940398
0.982832940398
CPU times: user 578 ms, sys: 164 ms, total: 742 ms
Wall time: 745 ms


In [501]:
%time w = Kernel(coords[:701], fixed=False, function='bisquare', truncate=True, k=100)

0.982832940398
(701, 101)
CPU times: user 3.99 s, sys: 5.97 ms, total: 4 s
Wall time: 4 s


In [502]:
np.allclose(gwrw.kernel, w.full()[0])

True

In [7]:
W = gwrw.kernel

In [504]:
b = w.full()[0]

In [505]:
np.allclose(a,b)

True

In [506]:
print len(a[~(a==b)])
print len(b[~(a==b)])


681
681


In [509]:
a[a<3.9999987967483774e-13] = 0.0
b[b<3.9999987967483774e-13] = 0.0

In [510]:
(a == b).all()

True

In [24]:
%timeit for x in np.arange(len(W)): np.diag(W[x])

1 loop, best of 3: 25.2 s per loop


In [12]:
def stuff(Wi):
    xtw = np.dot(X.T, Wi)
    xtwx = np.dot(xtw, X)
    xtwx_inv = np.linalg.inv(xtwx)
    xtwx_inv_xtw = np.dot(xtwx_inv, xtw)
    betas = np.dot(xtwx_inv_xtw, y)

In [14]:
%timeit for x in np.arange(5): stuff(np.diag(W[x]))

10 loops, best of 3: 60.8 ms per loop


In [10]:
Ws = [np.diag(W[x]) for x in np.arange(5)]

In [13]:
%timeit for x in Ws: stuff(x)

10 loops, best of 3: 23.1 ms per loop


In [22]:
%timeit for x in np.arange(5): np.diag(W[x])

10 loops, best of 3: 50.2 ms per loop


In [33]:
np.diagflat(W[0])

array([[ 1.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.98283294,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.93222356, ...,  0.        ,
         0.        ,  0.        ],
       ..., 
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ]])

In [33]:
n = np.dot(X.T, W[0].reshape((-1,1)))

In [34]:
m = np.dot(X.T, np.diag(W[0]))

In [35]:
n

array([[ 1611.97483753],
       [ 1535.31714558]])

In [52]:
(X*W[0].reshape((-1,1))).T

array([[ 39.15764514,   5.39885903,  63.81102046, ...,   0.        ,
          0.        ,   0.        ],
       [  4.27009448,  23.19474446,  10.53401934, ...,  -0.        ,
          0.        ,   0.        ]])

In [47]:
m

array([[ 39.15764514,   5.39885903,  63.81102046, ...,   0.        ,
          0.        ,   0.        ],
       [  4.27009448,  23.19474446,  10.53401934, ...,   0.        ,
          0.        ,   0.        ]])

In [54]:
%time mod = GWR(coords, y, X, 100).fit()

CPU times: user 2min 12s, sys: 19.4 s, total: 2min 31s
Wall time: 54.7 s


In [56]:
80*10/60

13

In [58]:
60*4*10

2400

In [59]:
2400/60

40