In [1]:
#Import GLM and pysal
import os
import numpy as np
os.chdir('/Users/toshan/projects/GIS596/pysal/pysal/contrib/gwr')
from glm import GLM
import pysal

In [2]:
#Prepare some test data - columbus example
db = pysal.open(pysal.examples.get_path('columbus.dbf'),'r')
y = np.array(db.by_col("HOVAL"))
y = np.reshape(y, (49,1))
X = []
X.append(db.by_col("INC"))
X.append(db.by_col("CRIME"))
X = np.array(X).T

In [ ]:
#First fit pysal OLS model

In [3]:
#Then fit Gaussian GLM

#create Gaussian GLM model object
model = GLM(y, X, 'Gaussian')
model

#Fit model to estimate coefficients and return GLMResults object
results = model.fit()

In [4]:
#Check coefficients
results.betas

array([[ 46.42818268],
       [  0.62898397],
       [ -0.48488854]])

In [5]:
#Check covariance
results.vm.diagonal()

array([  1.70319848e+02,   2.81089370e-01,   3.26594039e-02])

In [6]:
#check other diagnostics; need to be added! 

In [7]:
#Now fit a Poisson GLM - TODO get Poisson test data

#create Poisson GLM model object
model = GLM(y, X, 'Poisson')
model

#Fit model to estimate coefficients and return GLMResults object
results = model.fit()

In [8]:
#Check coefficients
results.betas

array([[ 3.91925951],
       [ 0.01198275],
       [-0.0137072 ]])

In [9]:
#Check covariance
results.vm.diagonal()

array([  1.70342025e-02,   2.61682548e-05,   3.75641476e-06])

In [10]:
#check other diagnostics; need to be added! 

In [11]:
#Now fit a binomial GLM - TODO get binomial test data

#create logistic GLM model object
model = GLM(y, X, 'logistic')
model

#Fit model to estimate coefficients and return GLMResults object
results = model.fit()

In [12]:
#Check coefficients
results.betas

array([[  9.04020835e+13],
       [  1.25167810e+12],
       [ -9.64928201e+11]])

In [13]:
#Check covariance
results.vm.diagonal()

array([  7.51857004e+09,   1.24083607e+07,   1.44171110e+06])

In [14]:
#check other diagnostics; need to be added! 