In [1]:
#Import GLM and pysal
import os
import numpy as np
#os.chdir('/Users/qszhao/Dropbox/pysal/pysal/contrib/gwr')
os.chdir('/Users/toshan/projects/GIS596/pysal/pysal/contrib/gwr')
from glm import GLM
import pysal
import pandas as pd
import statsmodels.formula.api as smf
import statsmodels.api as sm

In [2]:
#Prepare some test data - columbus example
db = pysal.open(pysal.examples.get_path('columbus.dbf'),'r')
y = np.array(db.by_col("HOVAL"))
y = np.reshape(y, (49,1))
X = []
#X.append(np.ones(len(y)))
X.append(db.by_col("INC"))
X.append(db.by_col("CRIME"))
X = np.array(X).T
print X

[[ 19.531     15.72598 ]
 [ 21.232     18.801754]
 [ 15.956     30.626781]
 [  4.477     32.38776 ]
 [ 11.252     50.73151 ]
 [ 16.028999  26.066658]
 [  8.438      0.178269]
 [ 11.337     38.425858]
 [ 17.586     30.515917]
 [ 13.598     34.000835]
 [  7.467     62.275448]
 [ 10.048     56.705669]
 [  9.549     46.716129]
 [  9.963     57.066132]
 [  9.873     48.585487]
 [  7.625     54.838711]
 [  9.798     36.868774]
 [ 13.185     43.962486]
 [ 11.618     54.521965]
 [ 31.07       0.223797]
 [ 10.655     40.074074]
 [ 11.709     33.705048]
 [ 21.155001  20.048504]
 [ 14.236     38.297871]
 [  8.461     61.299175]
 [  8.085     40.969742]
 [ 10.822     52.79443 ]
 [  7.856     56.919785]
 [  8.681     60.750446]
 [ 13.906     68.892044]
 [ 16.940001  17.677214]
 [ 18.941999  19.145592]
 [  9.918     41.968163]
 [ 14.948     23.974028]
 [ 12.814     39.175053]
 [ 18.739     14.305556]
 [ 17.017     42.445076]
 [ 11.107     53.710938]
 [ 18.476999  19.100863]
 [ 29.833     16.241299]


In [10]:
#First fit pysal OLS model
from pysal.spreg import ols
OLS = ols.OLS(y, X)
print OLS.betas

[[ 46.42818268]
 [  0.62898397]
 [ -0.48488854]]


In [11]:
#Then fit Gaussian GLM

#create Gaussian GLM model object
model = GLM(y, X, 'Gaussian')
model

#Fit model to estimate coefficients and return GLMResults object
results = model.fit()

#Check coefficients - R betas [46.4282, 0.6290, -0.4849]
print results.betas

TypeError: iwls() takes at most 9 arguments (10 given)

In [12]:
# Gaussian GLM results from statsmodels
sm_results = smf.OLS(y, sm.add_constant(X), ).fit()
print sm_results.params

[ 46.42818268   0.62898397  -0.48488854]


In [6]:
#check other diagnostics; need to be added! 

In [26]:
#Now fit a Poisson GLM 

poisson_y = np.round(y)

#create Poisson GLM model object
model = GLM(y, X, 'Poisson')
model

#Fit model to estimate coefficients and return GLMResults object
results = model.fit()

#Check coefficients - R betas [3.91926, 0.01198, -0.01371]
results.betas

TypeError: iwls() takes at most 9 arguments (10 given)

In [20]:
# Poisson GLM results from statsmodels
sm_results = smf.GLM(y, sm.add_constant(X), family=sm.families.Poisson()).fit()
print sm_results.params


[ 3.91925951  0.01198275 -0.0137072 ]


In [4]:
#Now fit a binomial GLM
londonhp = pd.read_csv('/Users/toshan/projects/londonhp.csv')
#londonhp = pd.read_csv('/Users/qszhao/Dropbox/pysal/pysal/contrib/gwr/londonhp.csv')
y = londonhp['BATH2'].values
y = np.reshape(y, (316,1))
X = londonhp['FLOORSZ'].values
X = np.reshape(X, (316,1))

#create logistic GLM model object
model = GLM(y, X, 'logistic')
model

#Fit model to estimate coefficients and return GLMResults object
results = model.fit()

#Check coefficients - R betas [-5.33638, 0.02878]
#results.betas

[[ 2.33075597]
 [ 2.33075597]
 [ 2.33075597]
 [ 2.33075597]
 [ 2.33075597]
 [ 2.33075597]
 [ 2.33075597]
 [ 2.33075597]
 [ 2.33075597]
 [-2.33075597]
 [ 2.33075597]
 [-2.33075597]
 [ 2.33075597]
 [ 2.33075597]
 [ 2.33075597]
 [ 2.33075597]
 [ 2.33075597]
 [ 2.33075597]
 [ 2.33075597]
 [ 2.33075597]
 [ 2.33075597]
 [-2.33075597]
 [ 2.33075597]
 [ 2.33075597]
 [ 2.33075597]
 [ 2.33075597]
 [ 2.33075597]
 [ 2.33075597]
 [ 2.33075597]
 [ 2.33075597]
 [ 2.33075597]
 [ 2.33075597]
 [ 2.33075597]
 [ 2.33075597]
 [ 2.33075597]
 [ 2.33075597]
 [-2.33075597]
 [ 2.33075597]
 [ 2.33075597]
 [-2.33075597]
 [ 2.33075597]
 [ 2.33075597]
 [ 2.33075597]
 [ 2.33075597]
 [ 2.33075597]
 [ 2.33075597]
 [ 2.33075597]
 [ 2.33075597]
 [ 2.33075597]
 [ 2.33075597]
 [ 2.33075597]
 [ 2.33075597]
 [ 2.33075597]
 [ 2.33075597]
 [-2.33075597]
 [-2.33075597]
 [ 2.33075597]
 [ 2.33075597]
 [ 2.33075597]
 [ 2.33075597]
 [-2.33075597]
 [ 2.33075597]
 [ 2.33075597]
 [ 2.33075597]
 [ 2.33075597]
 [ 2.33075597]
 [ 2.33075

TypeError: iwls() takes at most 9 arguments (10 given)

In [28]:
# Logistic GLM results from statsmodels
sm_results = smf.GLM(y, sm.add_constant(X), family=sm.families.Binomial()).fit()
print sm_results.params

[-5.33638276  0.0287754 ]


In [27]:
print X

[[ 77]
 [ 75]
 [ 64]
 [ 95]
 [107]
 [100]
 [ 81]
 [151]
 [ 98]
 [260]
 [171]
 [161]
 [ 91]
 [ 80]
 [ 50]
 [ 85]
 [ 52]
 [ 69]
 [ 60]
 [ 84]
 [155]
 [ 97]
 [ 69]
 [126]
 [ 90]
 [ 43]
 [ 51]
 [ 41]
 [140]
 [ 80]
 [ 52]
 [ 86]
 [ 66]
 [ 60]
 [ 40]
 [155]
 [138]
 [ 97]
 [115]
 [148]
 [206]
 [ 60]
 [ 53]
 [ 96]
 [ 88]
 [160]
 [ 31]
 [ 43]
 [154]
 [ 60]
 [131]
 [ 60]
 [ 46]
 [ 61]
 [125]
 [150]
 [ 76]
 [ 92]
 [ 96]
 [100]
 [105]
 [ 72]
 [ 48]
 [ 41]
 [ 72]
 [ 65]
 [ 60]
 [ 65]
 [ 98]
 [ 33]
 [144]
 [111]
 [ 91]
 [108]
 [ 38]
 [ 48]
 [ 95]
 [ 63]
 [ 98]
 [129]
 [108]
 [ 51]
 [131]
 [ 66]
 [ 48]
 [127]
 [ 76]
 [ 68]
 [ 52]
 [ 64]
 [ 57]
 [121]
 [ 67]
 [ 76]
 [112]
 [ 96]
 [ 90]
 [ 53]
 [ 93]
 [ 64]
 [ 97]
 [ 58]
 [ 44]
 [157]
 [ 53]
 [ 70]
 [ 71]
 [167]
 [ 47]
 [ 70]
 [ 96]
 [ 77]
 [ 75]
 [ 71]
 [ 67]
 [ 47]
 [ 71]
 [ 90]
 [ 69]
 [ 64]
 [ 65]
 [ 95]
 [ 60]
 [ 60]
 [ 65]
 [ 54]
 [121]
 [105]
 [ 50]
 [ 85]
 [ 69]
 [ 69]
 [ 62]
 [ 65]
 [ 93]
 [ 93]
 [ 70]
 [ 62]
 [155]
 [ 68]
 [117]
 [ 80]
 [ 80]