In [1]:
#Import GLM and pysal
import os
import numpy as np
#os.chdir('/Users/qszhao/Dropbox/pysal/pysal/contrib/gwr')
os.chdir('/Users/toshan/projects/GIS596/pysal/pysal/contrib/gwr')
from glm import GLM
import pysal
import pandas as pd
import statsmodels.formula.api as smf
import statsmodels.api as sm

In [2]:
#Prepare some test data - columbus example
db = pysal.open(pysal.examples.get_path('columbus.dbf'),'r')
y = np.array(db.by_col("HOVAL"))
y = np.reshape(y, (49,1))
X = []
X.append(db.by_col("INC"))
X.append(db.by_col("CRIME"))
X = np.array(X).T

In [3]:
#First fit pysal OLS model
from pysal.spreg import ols
OLS = ols.OLS(y, X)
print OLS.betas

[[ 46.42818268]
 [  0.62898397]
 [ -0.48488854]]


In [12]:
#Then fit Gaussian GLM

#create Gaussian GLM model object
model = GLM(y, X, 'Gaussian')
model

#Fit model to estimate coefficients and return GLMResults object
results = model.fit()

#Check coefficients - R betas [46.4282, 0.6290, -0.4849]
print results.betas

[[-0.17546668]
 [ 0.00300344]]


NameError: name 'GLMResults' is not defined

In [5]:
# Gaussian GLM results from statsmodels
sm_results = smf.OLS(y, sm.add_constant(X), ).fit()
print sm_results.params

[ 46.42818268   0.62898397  -0.48488854]


In [6]:
#check other diagnostics; need to be added! 

In [7]:
#Now fit a Poisson GLM 

poisson_y = np.round(y)

#create Poisson GLM model object
model = GLM(y, X, 'Poisson')
model

#Fit model to estimate coefficients and return GLMResults object
results = model.fit()

#Check coefficients - R betas [3.91926, 0.01198, -0.01371]
results.betas

array([[ 3.91925951],
       [ 0.01198275],
       [-0.0137072 ]])

In [8]:
# Poisson GLM results from statsmodels
sm_results = smf.GLM(y, sm.add_constant(X), family=sm.families.Poisson()).fit()
print sm_results.params

[ 3.91925951  0.01198275 -0.0137072 ]


In [9]:
#check other diagnostics; need to be added! 

In [10]:
#Now fit a binomial GLM
londonhp = pd.read_csv('/Users/toshan/projects/londonhp.csv')
#londonhp = pd.read_csv('/Users/qszhao/Dropbox/pysal/pysal/contrib/gwr/londonhp.csv')
y = londonhp['BATH2'].values
y = np.reshape(y, (316,1))
X = londonhp['FLOORSZ'].values
X = np.reshape(X, (316,1))

#create logistic GLM model object
model = GLM(y, X, 'logistic')
model

#Fit model to estimate coefficients and return GLMResults object
results = model.fit()

#Check coefficients - R betas [-5.33638, 0.02878]
results.betas

array([[-5.33638276],
       [ 0.0287754 ]])

In [11]:
# Logistic GLM results from statsmodels
sm_results = smf.GLM(y, sm.add_constant(X), family=sm.families.Binomial()).fit()
print sm_results.params

[-5.33638276  0.0287754 ]


In [12]:
#check other diagnostics; need to be added! 