In [1]:
import numpy as np
import pysal
import os
os.chdir('/Users/toshan/projects/GIS596//pysal/pysal/contrib/gwr')
from glm import GLM
from gwr import GWR
from sel_bw import Sel_BW
import pandas as pd

In [2]:
#Gaussian data (columbus dataset)
db = pysal.open(pysal.examples.get_path('columbus.dbf'),'r')
y = np.array(db.by_col("HOVAL"))
y = np.reshape(y, (49,1))
X = []
X.append(db.by_col("INC"))
X.append(db.by_col("CRIME"))
X = np.array(X).T
x_coord = db.by_col('X')
y_coord = db.by_col('Y')
coords = np.array(zip(x_coord, y_coord))

In [3]:
Gaussian_adapt_bisqaure = GWR(coords, y, X, 20, family = 'Gaussian', fixed=False, kernel='bisquare')

In [4]:
results = Gaussian_adapt_bisqaure.fit()
results.betas

array([[  6.70386652e+01,   2.75763599e-01,  -9.09212068e-01],
       [  6.75892378e+01,   1.61907101e-01,  -8.19406368e-01],
       [  6.19776461e+01,   3.33979852e-01,  -8.29717883e-01],
       [  6.65355970e+01,   1.15469575e-01,  -7.80006842e-01],
       [  3.81988860e+01,   5.89924460e-01,  -3.63327589e-01],
       [  4.59407383e+01,   9.67522535e-01,  -5.66577554e-01],
       [  6.78198156e+01,   1.07851591e-01,  -7.29758672e-01],
       [  6.53564479e+01,   3.29592532e-02,  -7.12934558e-01],
       [  1.63600608e+01,   2.31536338e+00,  -2.31012849e-01],
       [  4.02776655e+01,   1.17407303e+00,  -2.60557378e-01],
       [  4.26964600e+01,   2.35416973e+00,  -7.01030687e-01],
       [  4.58245390e+01,   2.64050102e+00,  -7.96008102e-01],
       [  5.37055359e+01,   1.98545849e+00,  -8.06499329e-01],
       [  4.68285832e+01,   2.88255991e+00,  -8.41349088e-01],
       [  2.34836787e+00,   3.45803674e+00,  -1.86271095e-01],
       [  2.53002722e+01,   3.55705278e+00,  -5.8792534

In [5]:
Gaussian_adapt_bisqaure = GWR(coords, y, X, 20, family = 'Gaussian', fixed=False, kernel='bisquare')
Gaussian_fixed_bisqaure = GWR(coords, y, X, 20, family = 'Gaussian', fixed=True, kernel='bisquare')

Gaussian_adapt_gaussian = GWR(coords, y, X, 20, family = 'Gaussian', fixed=False, kernel='gaussian')
Gaussian_fixed_gaussian = GWR(coords, y, X, 20, family = 'Gaussian', fixed=True, kernel='gaussian')

Gaussian_adapt_exponential = GWR(coords, y, X, 20, family = 'Gaussian', fixed=False, kernel='exponential')
Gaussian_fixed_exponential = GWR(coords, y, X, 20, family = 'Gaussian', fixed=True, kernel='exponential')

In [6]:
Gaussian_adapt_bisqaure_betas = Gaussian_adapt_bisqaure.fit().betas
Gaussian_fixed_bisqaure_betas = Gaussian_fixed_bisqaure.fit().betas

Gaussian_adapt_gaussian_betas = Gaussian_adapt_gaussian.fit().betas
Gaussian_fixed_gaussian_betas = Gaussian_fixed_gaussian.fit().betas

Gaussian_adapt_exponential_betas = Gaussian_adapt_exponential.fit().betas
Gaussian_fixed_exponential_betas = Gaussian_fixed_exponential.fit().betas

In [7]:
print Gaussian_adapt_bisqaure_betas.min(axis=0) # R - [-18.67000, 0.03296, -0.90920]
print Gaussian_adapt_bisqaure_betas.max(axis=0) # R - [67.8200, 3.5570, 0.2844]

[-18.66539664   0.03295925  -0.90921207]
[ 67.81981559   3.55705278   0.28442034]


In [8]:
print Gaussian_fixed_bisqaure_betas.min(axis=0) # R - [17.0400, 0.1162, -0.7056]
print Gaussian_fixed_bisqaure_betas.max(axis=0) # R - [58.6400, 1.6230, -0.1259]

[ 17.04432385   0.11620188  -0.70556914]
[ 58.64394425   1.6233218   -0.12592344]


In [9]:
print Gaussian_adapt_gaussian_betas.min(axis=0) # R - [23.0200, 0.3913, -0.6234]
print Gaussian_adapt_gaussian_betas.max(axis=0) # R - [55.2900, 1.5110, -0.2097]

[ 23.02000323   0.39128173  -0.623395  ]
[ 55.29020353   1.51138408  -0.2097182 ]


In [10]:
print Gaussian_fixed_gaussian_betas.min(axis=0) # R - [41.3500, 0.5657, -0.5267]
print Gaussian_fixed_gaussian_betas.max(axis=0) # R - [49.2700, 0.8166, -0.4255]

[ 41.345534     0.56565342  -0.52668753]
[ 49.26969564   0.81660591  -0.42548594]


In [11]:
print Gaussian_adapt_exponential_betas.min(axis=0) # - R [26.9200, 0.1948, -0.6379]
print Gaussian_adapt_exponential_betas.max(axis=0) # - R [59.4300, 1.3750, -0.2498]

[ 26.92346229   0.19476172  -0.6378932 ]
[ 59.43019197   1.37456823  -0.24984853]


In [12]:
print Gaussian_fixed_exponential_betas.min(axis=0) # R - [38.5700, 0.4129, -0.5660]
print Gaussian_fixed_exponential_betas.max(axis=0) # R - [52.8800, 0.8782, -0.3908]

[ 38.57033004   0.41290491  -0.56602362]
[ 52.87708079   0.87818724  -0.39075504]


In [13]:
y = np.round(y)

In [21]:
Poisson_adapt_bisqaure = GWR(coords, y, X, 45, family = 'Poisson', fixed=False, kernel='bisquare')
Poisson_fixed_bisqaure = GWR(coords, y, X, 21.59945, family = 'Poisson', fixed=True, kernel='bisquare')

Poisson_adapt_gaussian = GWR(coords, y, X, 25, family = 'Poisson', fixed=False, kernel='gaussian')
Poisson_fixed_gaussian = GWR(coords, y, X, 9.650319, family = 'Poisson', fixed=True, kernel='gaussian')

Poisson_adapt_exponential = GWR(coords, y, X, 25, family = 'Poisson', fixed=False, kernel='exponential')
Poisson_fixed_exponential = GWR(coords, y, X, 5.13043, family = 'Poisson', fixed=True, kernel='exponential')



In [22]:
Poisson_adapt_bisqaure_betas = Poisson_adapt_bisqaure.fit().betas
Poisson_fixed_bisqaure_betas = Poisson_fixed_bisqaure.fit().betas

Poisson_adapt_gaussian_betas = Poisson_adapt_gaussian.fit().betas
Poisson_fixed_gaussian_betas = Poisson_fixed_gaussian.fit().betas

Poisson_adapt_exponential_betas = Poisson_adapt_exponential.fit().betas
Poisson_fixed_exponential_betas = Poisson_fixed_exponential.fit().betas


In [23]:
print Poisson_adapt_bisqaure_betas.min(axis=0) # R - [2.866000, 0.004344, -0.017490]
print Poisson_adapt_bisqaure_betas.max(axis=0) # R - [4.1280, 0.0456, -0.0009]

[ 2.82938626  0.00449929 -0.01745889]
[  4.12681268e+00   4.67421257e-02  -4.70631158e-04]


In [24]:
print Poisson_fixed_bisqaure_betas.min(axis=0) # R - [3.292000, 0.002915, -0.017100]
print Poisson_fixed_bisqaure_betas.max(axis=0) # R - [4.1150, 0.0323, -0.0055]

[  3.28772908e+00   3.06862567e-03  -1.70188218e-02]
[ 4.11026967  0.03240893 -0.00553341]


In [25]:
print Poisson_adapt_gaussian_betas.min(axis=0) # R - [3.549000, 0.009156, -0.015570]
print Poisson_adapt_gaussian_betas.max(axis=0) # R - [4.0380, 0.0248, -0.0093]

[ 3.51957244  0.00912422 -0.01555608]
[ 4.03607667  0.02559906 -0.00893505]


In [26]:
print Poisson_fixed_gaussian_betas.min(axis=0) # R - [3.51400, 0.00699, -0.01665 ]
print Poisson_fixed_gaussian_betas.max(axis=0) # R - [4.0990, 0.0251, -0.0085]

[ 3.48963233  0.00702306 -0.01659919]
[ 4.09648988  0.02588597 -0.00822654]


In [174]:
print Poisson_adapt_exponential_betas.min(axis=0) # R - [3.577000, 0.005922, -0.016070]
print Poisson_adapt_exponential_betas.max(axis=0) # R - [4.1090, 0.0232, -0.0099]

[ 3.53577505  0.00588311 -0.01605733]
[ 4.10825814  0.02458137 -0.00937449]


In [175]:
print Poisson_fixed_exponential_betas.min(axis=0) # R - [3.206000, 0.003129, -0.019580]
print Poisson_fixed_exponential_betas.max(axis=0) # R - [4.2790, 0.0341, -0.0054]

[  3.11787614e+00   2.83238961e-03  -1.96323204e-02]
[ 4.24950552  0.03704991 -0.00426979]


In [30]:
#logistic data
londonhp = pd.read_csv('/Users/toshan/projects/londonhp.csv')
coords = zip(londonhp['coords.x1'], londonhp['coords.x2'])
y = londonhp['BATH2'].values
y = np.reshape(y, (316,1))
X = londonhp['FLOORSZ'].values
X = np.reshape(X, (316,1))

In [32]:
logistic_adapt_bisqaure = GWR(coords, y, X, 158, family = 'logistic', fixed=False, kernel='bisquare')
logistic_fixed_bisqaure = GWR(coords, y, X, 45292.61, family = 'logistic', fixed=True, kernel='bisquare')

logistic_adapt_gaussian = GWR(coords, y, X, 275, family = 'logistic', fixed=False, kernel='gaussian')
logistic_fixed_gaussian = GWR(coords, y, X, 45172.44, family = 'logistic', fixed=True, kernel='gaussian')

logistic_adapt_exponential = GWR(coords, y, X, 273, family = 'logistic', fixed=False, kernel='exponential')
logistic_fixed_exponential = GWR(coords, y, X, 45172.44, family = 'logistic', fixed=True, kernel='exponential')


In [33]:
logistic_adapt_bisqaure_betas = logistic_adapt_bisqaure.fit().betas
logistic_fixed_bisqaure_betas = logistic_fixed_bisqaure.fit().betas

logistic_adapt_gaussian_betas = logistic_adapt_gaussian.fit().betas
logistic_fixed_gaussian_betas = logistic_fixed_gaussian.fit().betas

logistic_adapt_exponential_betas = logistic_adapt_exponential.fit().betas
logistic_fixed_exponential_betas = logistic_fixed_exponential.fit().betas

In [41]:
print logistic_adapt_bisqaure_betas.min(axis=0) # R - [-9.08200, 0.01249]
print logistic_adapt_bisqaure_betas.max(axis=0) # R - [-3.1330, 0.0589]

[-12.41878011   0.0128016 ]
[-3.23982143  0.08240862]


In [42]:
print logistic_fixed_bisqaure_betas.min(axis=0) # R - [-6.08400, 0.02345]
print logistic_fixed_bisqaure_betas.max(axis=0) # R - [-4.5960, 0.0348]

[-6.19693558  0.02378626]
[-4.65522095  0.03561591]


In [43]:
print logistic_adapt_gaussian_betas.min(axis=0) # R - [-5.58800, 0.02630]
print logistic_adapt_gaussian_betas.max(axis=0) # R - [-5.0230, 0.0308]

[-5.60821994  0.0264057 ]
[-5.0388266   0.03093707]


In [44]:
print logistic_fixed_gaussian_betas.min(axis=0) # R - [-5.47400, 0.02761]
print logistic_fixed_gaussian_betas.max(axis=0) # R - [-5.1820, 0.0299]

[-5.47883357  0.02751334]
[-5.15534536  0.02990821]


In [45]:
print logistic_adapt_exponential_betas.min(axis=0) # R - [-5.74600, 0.02393]
print logistic_adapt_exponential_betas.max(axis=0) # R - [-4.6690, 0.0322]

[-5.80518578  0.02433976]
[-4.73220017  0.03265618]


In [46]:
print logistic_fixed_exponential_betas.min(axis=0) # R - [-5.62000, 0.02601]
print logistic_fixed_exponential_betas.max(axis=0) # R - [-4.9810, 0.0312]

[-5.64633884  0.02610508]
[-5.00030119  0.03143528]
