In [1]:
import numpy as np
import pysal
import os
os.chdir('/Users/toshan/dev/pysal/pysal/contrib/glm')

from family import Gaussian, Binomial, Poisson
os.chdir('/Users/toshan/dev/pysal/pysal/contrib/gwr')
from gwr import GWR
from sel_bw import Sel_BW
import pandas as pd

In [2]:
#Gaussian data (columbus dataset)

db = pysal.open(pysal.examples.get_path('columbus.dbf'),'r')
y = np.array(db.by_col("HOVAL"))
y = np.reshape(y, (49,1))
X = []
X.append(db.by_col("INC"))
X.append(db.by_col("CRIME"))
X = np.array(X).T
x_coord = db.by_col('X')
y_coord = db.by_col('Y')
coords = np.array(zip(x_coord, y_coord))

In [3]:
#Instantiate Gaussian GWR model with fixed bisquare kernel

Gaussian_adapt_bisqaure = GWR(coords, y, X, 20, family=Gaussian(), fixed=False, kernel='bisquare')

In [102]:
#Fit model, and check out local coefficents 

results = Gaussian_adapt_bisqaure.fit()
results.params

array([[  6.70386652e+01,   2.75763599e-01,  -9.09212068e-01],
       [  6.75892378e+01,   1.61907101e-01,  -8.19406368e-01],
       [  6.19776461e+01,   3.33979852e-01,  -8.29717883e-01],
       [  6.65355970e+01,   1.15469575e-01,  -7.80006842e-01],
       [  3.81988860e+01,   5.89924460e-01,  -3.63327589e-01],
       [  4.59407383e+01,   9.67522535e-01,  -5.66577554e-01],
       [  6.78198156e+01,   1.07851591e-01,  -7.29758672e-01],
       [  6.53564479e+01,   3.29592532e-02,  -7.12934558e-01],
       [  1.63600608e+01,   2.31536338e+00,  -2.31012849e-01],
       [  4.02776655e+01,   1.17407303e+00,  -2.60557378e-01],
       [  4.26964600e+01,   2.35416973e+00,  -7.01030687e-01],
       [  4.58245390e+01,   2.64050102e+00,  -7.96008102e-01],
       [  5.37055359e+01,   1.98545849e+00,  -8.06499329e-01],
       [  4.68285832e+01,   2.88255991e+00,  -8.41349088e-01],
       [  2.34836787e+00,   3.45803674e+00,  -1.86271095e-01],
       [  2.53002722e+01,   3.55705278e+00,  -5.8792534

In [103]:
#Instantiate Gaussian GWR models for both fixed and dadaptive bandwidths using bisqaure, gaussian or exponential kernels

Gaussian_adapt_bisqaure = GWR(coords, y, X, 20, family=Gaussian(), fixed=False, kernel='bisquare')
Gaussian_fixed_bisqaure = GWR(coords, y, X, 20, family=Gaussian(), fixed=True, kernel='bisquare')

Gaussian_adapt_gaussian = GWR(coords, y, X, 20, family=Gaussian(), fixed=False, kernel='gaussian')
Gaussian_fixed_gaussian = GWR(coords, y, X, 20, family=Gaussian(), fixed=True, kernel='gaussian')

Gaussian_adapt_exponential = GWR(coords, y, X, 20, family=Gaussian(), fixed=False, kernel='exponential')
Gaussian_fixed_exponential = GWR(coords, y, X, 20, family=Gaussian(), fixed=True, kernel='exponential')

In [106]:
#Fit coefficients for each model; extract coefficients

Gaussian_adapt_bisqaure_betas = Gaussian_adapt_bisqaure.fit().params
Gaussian_fixed_bisqaure_betas = Gaussian_fixed_bisqaure.fit().params

Gaussian_adapt_gaussian_betas = Gaussian_adapt_gaussian.fit().params
Gaussian_fixed_gaussian_betas = Gaussian_fixed_gaussian.fit().params

Gaussian_adapt_exponential_betas = Gaussian_adapt_exponential.fit().params
Gaussian_fixed_exponential_betas = Gaussian_fixed_exponential.fit().params

In [107]:
#Check min and max coefficient values  with those from GWModel in R
#Gaussian; adaptive bisquare

print Gaussian_adapt_bisqaure_betas.min(axis=0) # R - [-18.67000, 0.03296, -0.90920]
print Gaussian_adapt_bisqaure_betas.max(axis=0) # R - [67.8200, 3.5570, 0.2844]

[-18.66539664   0.03295925  -0.90921207]
[ 67.81981559   3.55705278   0.28442034]


In [108]:
#Check min and max coefficient values  with those from GWModel in R
#Gaussian; fixed bisquare

print Gaussian_fixed_bisqaure_betas.min(axis=0) # R - [17.0400, 0.1162, -0.7056]
print Gaussian_fixed_bisqaure_betas.max(axis=0) # R - [58.6400, 1.6230, -0.1259]

[ 17.04432385   0.11620188  -0.70556914]
[ 58.64394425   1.6233218   -0.12592344]


In [109]:
#Check min and max coefficient values  with those from GWModel in R
#Gaussian; adaptive Gaussian

print Gaussian_adapt_gaussian_betas.min(axis=0) # R - [23.0200, 0.3913, -0.6234]
print Gaussian_adapt_gaussian_betas.max(axis=0) # R - [55.2900, 1.5110, -0.2097]

[ 23.02000323   0.39128173  -0.623395  ]
[ 55.29020353   1.51138408  -0.2097182 ]


In [110]:
#Check min and max coefficient values  with those from GWModel in R
#Gaussian; fixed Gaussian

print Gaussian_fixed_gaussian_betas.min(axis=0) # R - [41.3500, 0.5657, -0.5267]
print Gaussian_fixed_gaussian_betas.max(axis=0) # R - [49.2700, 0.8166, -0.4255]

[ 41.345534     0.56565342  -0.52668753]
[ 49.26969564   0.81660591  -0.42548594]


In [111]:
#Check min and max coefficient values  with those from GWModel in R
#Gaussian; adaptive exponential

print Gaussian_adapt_exponential_betas.min(axis=0) # - R [26.9200, 0.1948, -0.6379]
print Gaussian_adapt_exponential_betas.max(axis=0) # - R [59.4300, 1.3750, -0.2498]

[ 26.92346229   0.19476172  -0.6378932 ]
[ 59.43019197   1.37456823  -0.24984853]


In [112]:
#Check min and max coefficient values  with those from GWModel in R
#Gaussian; fixed exponential

print Gaussian_fixed_exponential_betas.min(axis=0) # R - [38.5700, 0.4129, -0.5660]
print Gaussian_fixed_exponential_betas.max(axis=0) # R - [52.8800, 0.8782, -0.3908]

[ 38.57033004   0.41290491  -0.56602362]
[ 52.87708079   0.87818724  -0.39075504]


In [113]:
#convert Y into integer data for Poisson models

y = np.round(y)

In [114]:
#Instantiate Poisson GWR models for both fixed and dadaptive bandwidths using bisqaure, gaussian or exponential kernels

Poisson_adapt_bisqaure = GWR(coords, y, X, 45, family = Poisson(), fixed=False, kernel='bisquare')
Poisson_fixed_bisqaure = GWR(coords, y, X, 21.59945, family = Poisson(), fixed=True, kernel='bisquare')

Poisson_adapt_gaussian = GWR(coords, y, X, 25, family = Poisson(), fixed=False, kernel='gaussian')
Poisson_fixed_gaussian = GWR(coords, y, X, 9.650319, family = Poisson(), fixed=True, kernel='gaussian')

Poisson_adapt_exponential = GWR(coords, y, X, 25, family = Poisson(), fixed=False, kernel='exponential')
Poisson_fixed_exponential = GWR(coords, y, X, 5.13043, family = Poisson(), fixed=True, kernel='exponential')



In [115]:
#Fit coefficients for each model; extract coefficients

Poisson_adapt_bisqaure_betas = Poisson_adapt_bisqaure.fit().params
Poisson_fixed_bisqaure_betas = Poisson_fixed_bisqaure.fit().params

Poisson_adapt_gaussian_betas = Poisson_adapt_gaussian.fit().params
Poisson_fixed_gaussian_betas = Poisson_fixed_gaussian.fit().params

Poisson_adapt_exponential_betas = Poisson_adapt_exponential.fit().params
Poisson_fixed_exponential_betas = Poisson_fixed_exponential.fit().params


In [116]:
#Check min and max coefficient values  with those from GWModel in R
#Poisson; adaptive bisquare

print Poisson_adapt_bisqaure_betas.min(axis=0) # R - [2.866000, 0.004344, -0.017490]
print Poisson_adapt_bisqaure_betas.max(axis=0) # R - [4.1280, 0.0456, -0.0009]

[ 2.82933952  0.00449942 -0.01745933]
[  4.12679797e+00   4.67432738e-02  -4.70670075e-04]


In [117]:
#Check min and max coefficient values  with those from GWModel in R
#Poisson; fixed bisquare

print Poisson_fixed_bisqaure_betas.min(axis=0) # R - [3.292000, 0.002915, -0.017100]
print Poisson_fixed_bisqaure_betas.max(axis=0) # R - [4.1150, 0.0323, -0.0055]

[  3.28769774e+00   3.06871720e-03  -1.70192553e-02]
[ 4.11025492  0.03240957 -0.00553361]


In [118]:
#Check min and max coefficient values  with those from GWModel in R
#Poisson; adaptive Gaussian

print Poisson_adapt_gaussian_betas.min(axis=0) # R - [3.549000, 0.009156, -0.015570]
print Poisson_adapt_gaussian_betas.max(axis=0) # R - [4.0380, 0.0248, -0.0093]

[ 3.51954647  0.00912442 -0.0155565 ]
[ 4.0360612   0.02559954 -0.00893534]


In [119]:
#Check min and max coefficient values  with those from GWModel in R
#Poisson; fixed Gaussian

print Poisson_fixed_gaussian_betas.min(axis=0) # R - [3.51400, 0.00699, -0.01665 ]
print Poisson_fixed_gaussian_betas.max(axis=0) # R - [4.0990, 0.0251, -0.0085]

[ 3.48960593  0.00702321 -0.01659962]
[ 4.09647504  0.02588646 -0.00822681]


In [120]:
#Check min and max coefficient values  with those from GWModel in R
#Poisson; adaptive exponential

print Poisson_adapt_exponential_betas.min(axis=0) # R - [3.577000, 0.005922, -0.016070]
print Poisson_adapt_exponential_betas.max(axis=0) # R - [4.1090, 0.0232, -0.0099]

[ 3.53577516  0.00588311 -0.01605733]
[ 4.10825814  0.02458137 -0.00937449]


In [21]:
#Check min and max coefficient values  with those from GWModel in R
#Poisson; fixed exponential

print Poisson_fixed_exponential_betas.min(axis=0) # R - [3.206000, 0.003129, -0.019580]
print Poisson_fixed_exponential_betas.max(axis=0) # R - [4.2790, 0.0341, -0.0054]

[  3.11787614e+00   2.83238961e-03  -1.96323204e-02]
[ 4.24950552  0.03704991 -0.00426979]


In [43]:
#Load binary data for binomial/logistic model

londonhp = pd.read_csv('/Users/toshan/projects/londonhp.csv')
#londonhp = pd.read_csv('/Users/qszhao/Dropbox/pysal/pysal/contrib/gwr/londonhp.csv')
coords = zip(londonhp['coords.x1'], londonhp['coords.x2'])
y = londonhp['BATH2'].values
y = np.reshape(y, (316,1))
X = londonhp['FLOORSZ'].values
X = np.reshape(X, (316,1))

In [23]:
#Instantiate Poisson GWR models for both fixed and dadaptive bandwidths using bisqaure, gaussian or exponential kernels

logistic_adapt_bisqaure = GWR(coords, y, X, 158, family = Binomial(), fixed=False, kernel='bisquare')
logistic_fixed_bisqaure = GWR(coords, y, X, 45292.61, family = Binomial(), fixed=True, kernel='bisquare')

logistic_adapt_gaussian = GWR(coords, y, X, 275, family = Binomial(), fixed=False, kernel='gaussian')
logistic_fixed_gaussian = GWR(coords, y, X, 45172.44, family = Binomial(), fixed=True, kernel='gaussian')

logistic_adapt_exponential = GWR(coords, y, X, 273, family = Binomial(), fixed=False, kernel='exponential')
logistic_fixed_exponential = GWR(coords, y, X, 45172.44, family = Binomial(), fixed=True, kernel='exponential')


In [24]:
#Fit coefficients for each model; extract coefficients

logistic_adapt_bisqaure_betas = logistic_adapt_bisqaure.fit().betas
logistic_fixed_bisqaure_betas = logistic_fixed_bisqaure.fit().betas

logistic_adapt_gaussian_betas = logistic_adapt_gaussian.fit().betas
logistic_fixed_gaussian_betas = logistic_fixed_gaussian.fit().betas

logistic_adapt_exponential_betas = logistic_adapt_exponential.fit().betas
logistic_fixed_exponential_betas = logistic_fixed_exponential.fit().betas

In [25]:
#Check min and max coefficient values  with those from GWModel in R
#Binomial; adapt bisquare

print logistic_adapt_bisqaure_betas.min(axis=0) # R - [-9.08200, 0.01249]
print logistic_adapt_bisqaure_betas.max(axis=0) # R - [-3.1330, 0.0589]

[-12.41852536   0.0128016 ]
[-3.23982143  0.08240689]


In [26]:
#Check min and max coefficient values  with those from GWModel in R
#Binomial; fixed bisquare

print logistic_fixed_bisqaure_betas.min(axis=0) # R - [-6.08400, 0.02345]
print logistic_fixed_bisqaure_betas.max(axis=0) # R - [-4.5960, 0.0348]

[-6.19693579  0.02378626]
[-4.65522095  0.03561591]


In [27]:
#Check min and max coefficient values  with those from GWModel in R
#Poisson; adaptive Gaussian

print logistic_adapt_gaussian_betas.min(axis=0) # R - [-5.58800, 0.02630]
print logistic_adapt_gaussian_betas.max(axis=0) # R - [-5.0230, 0.0308]

[-5.60821994  0.0264057 ]
[-5.03882661  0.03093707]


In [28]:
#Check min and max coefficient values  with those from GWModel in R
#Binomial; fixed Gaussian

print logistic_fixed_gaussian_betas.min(axis=0) # R - [-5.47400, 0.02761]
print logistic_fixed_gaussian_betas.max(axis=0) # R - [-5.1820, 0.0299]

[-5.47883357  0.02764312]
[-5.18638926  0.02990821]


In [29]:
#Check min and max coefficient values  with those from GWModel in R
#Binomial; adaptive exponential

print logistic_adapt_exponential_betas.min(axis=0) # R - [-5.74600, 0.02393]
print logistic_adapt_exponential_betas.max(axis=0) # R - [-4.6690, 0.0322]

[-5.80518578  0.02433976]
[-4.73220017  0.03265618]


In [30]:
#Check min and max coefficient values  with those from GWModel in R
#Binomial; fixed exponential

print logistic_fixed_exponential_betas.min(axis=0) # R - [-5.62000, 0.02601]
print logistic_fixed_exponential_betas.max(axis=0) # R - [-4.9810, 0.0312]

[-5.64633884  0.02610508]
[-5.00030119  0.03143528]


In [48]:
bw = Sel_BW(coords, y, X, [], family=Binomial(), fixed=False, kernel='bisquare')

In [50]:
bw.search(criterion='CV', bw_min = 156, bw_max=160)

28.944609303
28.6662266164
28.4694226436
28.6662266164


158.0

In [2]:
tokyo = pd.read_csv('/Users/toshan/Dropbox/dev/GWR4/tokyo/tokyomortality.csv')
y = tokyo.db2564.values.reshape((-1,1))
X = np.hstack([tokyo.POP65.values.reshape((-1,1)), tokyo.UNEMP.values.reshape((-1,1)), tokyo.OCC_TEC.values.reshape((-1,1)), tokyo.OWNH.values.reshape((-1,1))])
off = tokyo.eb2564.values.reshape((-1,1))
coords = np.array(zip(tokyo.X_CENTROID, tokyo.Y_CENTROID))

In [3]:
bw = Sel_BW(coords, y, X, [], family=Poisson(), y_off=off, kernel='bisquare', fixed=False)

In [4]:
test = bw.search(criterion='AICc_GLM')

bisquare
True
50 262
0.0
0.0
0.0
0.0


In [5]:
bw.bw

(131.0, 12.329411764705883, [(131.0, 12.329411764705883)])

In [9]:
Gaussian_adapt_bisqaure
results = Gaussian_adapt_bisqaure.fit()

In [6]:
results.logll

-200.37418882030795

In [7]:
results.t_stat[0,:]

array([ 2.67950687,  0.01102215, -0.03634082])

In [9]:
results.tvalues[0,:]

array([ 40.38590407,   0.16612745,  -0.54773393])

In [7]:
results.bse

array([ 1.65995207])

In [11]:
results.aic

382.32470023243638

In [25]:
print results.llf
print results.logll

-193.88830326
-189.763289177


In [10]:
results.u

array([ 22.34064978, -11.05357146, -15.54504076,  -8.5898789 ,
        -3.17955878, -17.93037269,   6.40022603,  -1.20998488,
         2.57152564,  49.01645992,   3.0819557 ,  -7.31812136,
         6.71184874,  15.36501248,  -9.43949273,  -1.38173279,
        -0.65772588,  13.26104187,  -4.06376536,   6.49767353,
       -10.06813136,  -1.15112351,  -7.06650036,   4.95017631,
        -1.13195162,  -1.24652977,   4.44585929,   0.25035649,
        10.41470731,  -5.11453264,  -9.57507632,  -7.94077088,
         0.33667207,  -7.26920695,  -2.72765268,  -7.59669733,
         5.3936923 ,  -4.01468821,  -3.99749412,  -2.16371067,
        -7.99408542,  -5.75999657,  -3.47932813,  -2.65735155,
        -2.37434457,  31.93527967,   0.94642035,   0.92687514,  -1.98068235])

In [21]:
r2 = (results.TSS - results.RSS)/results.TSS

print results.TSS[0], results.RSS[0]
print results.TSS[0] - results.RSS[0]

[  1.09691694e+09] [ 40842.85940702]
[  1.09687610e+09]


In [29]:
os.chdir('/Users/toshan/dev/pysal/pysal/contrib/gwr/examples/georgia')
data = pysal.open('georgia/GData_utm.csv')
coords = zip(data.by_col('X'), data.by_col('Y'))
y = np.array(data.by_col('PctBach')).reshape((-1,1))
rural  = np.array(data.by_col('PctRural')).reshape((-1,1))
pov = np.array(data.by_col('PctPov')).reshape((-1,1)) 
black = np.array(data.by_col('PctBlack')).reshape((-1,1))
X = np.hstack([rural, pov, black])


In [30]:
model = GWR(coords, y, X, 209267.689, family=Gaussian(), fixed=True, kernel='bisquare').fit()

In [31]:
model.utu

2012.5639251354789

In [5]:
model.bse

array([[ 2.61392525,  0.02253418,  0.12315202,  0.0538287 ],
       [ 2.85100388,  0.02393733,  0.13479555,  0.05738473],
       [ 2.73823514,  0.02322302,  0.12682592,  0.05789803],
       [ 2.59435705,  0.02330475,  0.13341192,  0.06062406],
       [ 1.44097525,  0.01615044,  0.08697448,  0.03981027],
       [ 1.62141227,  0.02095444,  0.13444197,  0.04322644],
       [ 1.51840353,  0.01908222,  0.12323235,  0.03983134],
       [ 1.90866092,  0.02238803,  0.14491758,  0.04894839],
       [ 2.29304153,  0.01921761,  0.10286162,  0.04175925],
       [ 2.74220389,  0.02279747,  0.13260245,  0.05283194],
       [ 1.37549611,  0.01552426,  0.08432588,  0.03898453],
       [ 1.66250237,  0.01702207,  0.08358805,  0.03894966],
       [ 3.53674843,  0.02899009,  0.16651941,  0.08587273],
       [ 3.42665347,  0.02744305,  0.16760371,  0.06478423],
       [ 3.26502347,  0.0282637 ,  0.16705917,  0.06879721],
       [ 2.56411371,  0.02458994,  0.14159617,  0.05091403],
       [ 2.52223901,  0.

In [2]:
os.chdir('/Users/toshan/dev/pysal/pysal/contrib/gwr/examples/tokyo')
data = pysal.open('tokyo/tokyomortality.csv', mode='rU')
coords = zip(data.by_col('X_CENTROID'), data.by_col('Y_CENTROID'))
y = np.array(data.by_col('db2564')).reshape((-1,1))
off = np.array(data.by_col('eb2564')).reshape((-1,1))
OCC  = np.array(data.by_col('OCC_TEC')).reshape((-1,1))
OWN = np.array(data.by_col('OWNH')).reshape((-1,1)) 
POP = np.array(data.by_col('POP65')).reshape((-1,1))
UNEMP = np.array(data.by_col('UNEMP')).reshape((-1,1))
X = np.hstack([OCC,OWN,POP,UNEMP])


In [3]:
model = GWR(coords, y, X, 26029.625, family=Poisson(), fixed=True, kernel='bisquare', sigma2_v1=True)
model = model.fit()

ValueError: operands could not be broadcast together with shapes (262,5) (262,) 

In [4]:
model.bse

array([[ 0.37835376,  0.70215902,  0.17153834,  1.02289713,  0.05057966],
       [ 0.16562405,  0.74770613,  0.17754943,  0.61585974,  0.02751086],
       [ 0.15859374,  0.37276704,  0.08706239,  0.5509769 ,  0.03337558],
       ..., 
       [ 0.22266591,  0.60257794,  0.23749188,  0.66509624,  0.02649677],
       [ 0.15380346,  0.35686261,  0.08616235,  0.4558456 ,  0.02435527],
       [ 0.24764401,  0.58658112,  0.121654  ,  0.70182014,  0.03659281]])

In [8]:

np.trace((model.S**2))

0.48125019674153835

In [27]:
model.tr_STS

0.8980047540699142

In [28]:
model.deviance

15889.152719905622

In [8]:
np.sum(np.dot(model.u, model.u.T))

1923837.4110855805

In [9]:
np.sum(model.sig2)

17056.768351373827

In [5]:
model.tr_S

7.8902803571196287

In [6]:
np.trace(np.dot(model.S.T, model.S))

0.8980047540699142

In [21]:
model.X[0]

array([ 1.   ,  0.126,  0.606,  0.104,  2.865])

In [22]:
model.z

AttributeError: 'GWRResults' object has no attribute 'z'

In [14]:
np.dot(model.X.T, np.dot(model.W, np.dot(model.w, model.X)))

ValueError: shapes (262,1) and (262,5) not aligned: 1 (dim 1) != 262 (dim 0)

In [29]:
XTW = np.dot(model.X.T, model.W)

In [30]:
XTWw = np.dot(XTW, model.w)

In [33]:
XTWwX = np.dot(model.X, XTWw)

In [35]:
XTWwX.shape

(262, 1)

In [37]:
Ww = np.dot(model.W, model.w)

In [39]:
XtX = np.dot(model.X.T, model.X)

In [45]:
np.dot(XtX, model.w)

ValueError: shapes (5,5) and (262,1) not aligned: 5 (dim 1) != 262 (dim 0)

In [10]:

f = model.f
cf = model.cf
cf[1]

array([  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,

In [1]:
C = np.zeros((model.n, model.k))
for i in range(model.n):
    Wi = np.diag(model.W[i])
    XTW = np.dot(model.X.T, Wi)
    XTWX = np.dot(XTW, model.X)
    XTWX_inv = np.linalg.inv(XTWX)
    Ci = np.dot(XTWX_inv, XTW)
    #C[i,:] = np.diag(np.dot(Ci , Ci.T*(1.0/model.w[i].reshape((-1,1)))))

NameError: name 'np' is not defined

In [6]:
se = np.sqrt(C)

In [15]:
sig2 = model.RSS/(model.n - 2.0*model.tr_S + model.tr_STS)

In [7]:
se

array([[ 1.75812034,  3.97659827,  0.92136471,  4.14571787,  0.25608698],
       [ 1.22627187,  4.62450047,  1.07537743,  3.50994834,  0.17927183],
       [ 1.2978241 ,  4.61842976,  0.70296798,  3.58461815,  0.24573769],
       ..., 
       [ 2.35726236,  7.71812446,  2.15235029,  7.18872758,  0.6066926 ],
       [ 1.20755915,  3.49956144,  0.97780033,  3.21336846,  0.21444612],
       [ 2.06935841,  7.03931103,  1.75897198,  5.21830151,  0.40166701]])

In [25]:
se[50]

array([ 3.0482007 ,  0.02792654,  0.16977254,  0.06377365])

In [39]:
np.dot(CtC, (1.0/model.mu.reshape((-1,1))))

ValueError: shapes (5,) and (262,1) not aligned: 5 (dim 0) != 262 (dim 0)

In [8]:
np.diag(np.dot(Ci , Ci.T*(1.0)))

array([  12.79272321,  177.83811567,   10.0804927 ,   94.21999986,
          0.53902367])

In [15]:
C[i] = np.diag(np.dot(Ci , Ci.T*(1.0/model.w)))

AttributeError: 'GWR' object has no attribute 'w'

In [11]:
Ci.shape

(5, 262)

In [53]:
model.

array([[  57.8331937 ,    0.        ,   10.3943621 , ...,    0.        ,
           0.        ,    0.        ],
       [   6.50409496,    0.        ,    1.16571128, ...,    0.        ,
           0.        ,    0.        ],
       [  43.41443302,    0.        ,    7.82909196, ...,    0.        ,
           0.        ,    0.        ],
       [   6.73969029,    0.        ,    1.21619378, ...,    0.        ,
           0.        ,    0.        ],
       [ 134.52410457,    0.        ,   24.06578841, ...,    0.        ,
           0.        ,    0.        ]])

In [28]:
model.w.shape

(159, 1)

In [8]:
model.params

array([[  3.73383673,   7.60428626,  -2.41501238,  -3.54658343,
          0.71662806],
       [  7.63348065,   5.98606283,  -5.48485964,   7.35866403,
         -0.28491679],
       [  6.3705547 ,   5.51539375,  -3.51189692,  -5.8978989 ,
          0.15502181],
       ..., 
       [  4.42634546,   3.01348859,  -7.18932933,  -5.15338449,
          1.77171022],
       [  0.83889118,  20.22746793,  -1.09416638, -11.06164227,
          1.03231269],
       [  1.06890403,  30.02234123,  -2.97528076,  -8.40882731,
          0.79367044]])

In [7]:
model.tr_S

2.1886673574466924

In [8]:
model.tr_STS

0.090910796730595267