In [1]:
import pysal as ps
import numpy as np
import os
os.chdir('/Users/toshan/projects/GIS596/pysal/pysal/weights/')
from Distance import Kernel, knnW
from pysal.cg.kdtree import KDTree
from scipy.spatial.distance import cdist

In [2]:
points=[(10, 10), (20, 10), (40, 10), (15, 20), (30, 20), (30, 30)]


def fix_gauss(points, bw):
    w = Kernel(points, function='bisquare', bandwidth=bw, diagonal=True, truncate=False)
    return w



w = fix_gauss(points, 15)
print w.full()[0]

[[ 1.          0.30864198  9.          0.19753086  1.49382716  6.5308642 ]
 [ 0.30864198  1.          0.60493827  0.19753086  0.01234568  1.49382716]
 [ 9.          0.60493827  1.          4.9382716   0.01234568  1.49382716]
 [ 0.19753086  0.19753086  4.9382716   1.          0.          0.19753086]
 [ 1.49382716  0.01234568  0.01234568  0.          1.          0.30864198]
 [ 6.5308642   1.49382716  1.49382716  0.19753086  0.30864198  1.        ]]


In [3]:
points=[(10, 10), (20, 10), (40, 10), (15, 20), (30, 20), (30, 30)]


def fix_gauss(points, bw):
    w = Kernel(points, fixed=False, k=bw, function='bisquare', diagonal=True, truncate=False)
    return w




w = fix_gauss(points,4)
print w.full()[0]

[[  1.00000000e+00   7.65625044e-01   1.56249438e-02   7.11914115e-01
    1.40625094e-01   3.99999881e-14]
 [  5.62500075e-01   1.00000000e+00   3.99999881e-14   4.72656336e-01
    2.50000100e-01   6.24998750e-02]
 [  5.82638516e-02   2.00951347e-01   1.00000000e+00   3.99999881e-14
    5.24375823e-01   9.63139976e-02]
 [  3.78698320e-01   3.78698320e-01   1.51479180e+00   1.00000000e+00
    9.46746414e-02   3.99999881e-14]
 [  1.49382607e+00   1.23457185e-02   1.23457185e-02   3.99999881e-14
    1.00000000e+00   3.08642074e-01]
 [  3.59999616e-01   3.99999881e-14   3.99999881e-14   1.22500091e-01
    6.40000064e-01   1.00000000e+00]]


In [4]:
os.chdir('/Users/toshan/projects/GIS596/pysal/pysal/contrib/gwr/legacy_gwr/')
from Kernel import get_pairDist, fix_Gaussian, adap_Bisquare
points={0:(10, 10), 1:(20, 10), 2:(40, 10), 3:(15, 20), 4:(30, 20), 5:(30, 30)}

dists = get_pairDist(points)
print adap_Bisquare(dists, 5)

{0: [1.0, 0.765625, 0.0, 0.7119140625, 0.14062499999999992, 0.0], 1: [0.5625, 1.0, 0.0, 0.47265625, 0.24999999999999989, 0.0], 2: [0.0, 0.20095124851367421, 1.0, 0.0, 0.52437574316290114, 0.096313912009512392], 3: [0.37869822485207105, 0.37869822485207105, 0.0, 1.0, 0.094674556213017694, 0.0], 4: [0.0, 0.01234567901234569, 0.01234567901234569, 0.0, 1.0, 0.30864197530864201], 5: [0.0, 0.0, 0.0, 0.12250000000000007, 0.64000000000000012, 1.0]}


In [12]:
np.exp((-1.0/2.0)*(20.0/5.0)**2)

0.00033546262790251185

In [5]:
range(len(points))

SyntaxError: unexpected EOF while parsing (<ipython-input-5-d09ad39bfecc>, line 1)

In [23]:
points=[(10, 10), (20, 10), (40, 10), (15, 20), (30, 20), (30, 30)]

In [41]:
pdists = pdist(points)
cdists = cdist(points, points)

In [33]:
np.min(dists[dists > 0])

10.0

In [44]:
pdists

array([ 10.        ,  30.        ,  11.18033989,  22.36067977,
        28.28427125,  20.        ,  11.18033989,  14.14213562,
        22.36067977,  26.92582404,  14.14213562,  22.36067977,
        15.        ,  18.02775638,  10.        ])

In [43]:
np.unique(cdists)

array([  0.        ,  10.        ,  11.18033989,  14.14213562,
        15.        ,  18.02775638,  20.        ,  22.36067977,
        26.92582404,  28.28427125,  30.        ])

In [47]:
cdists

array([[  0.        ,  10.        ,  30.        ,  11.18033989,
         22.36067977,  28.28427125],
       [ 10.        ,   0.        ,  20.        ,  11.18033989,
         14.14213562,  22.36067977],
       [ 30.        ,  20.        ,   0.        ,  26.92582404,
         14.14213562,  22.36067977],
       [ 11.18033989,  11.18033989,  26.92582404,   0.        ,
         15.        ,  18.02775638],
       [ 22.36067977,  14.14213562,  14.14213562,  15.        ,
          0.        ,  10.        ],
       [ 28.28427125,  22.36067977,  22.36067977,  18.02775638,
         10.        ,   0.        ]])

array([[  0.        ,  10.        ,  30.        ,  11.18033989,
         22.36067977,  28.28427125],
       [ 10.        ,   0.        ,  20.        ,  11.18033989,
         14.14213562,  22.36067977],
       [ 30.        ,  20.        ,   0.        ,  26.92582404,
         14.14213562,  22.36067977],
       [ 11.18033989,  11.18033989,  26.92582404,   0.        ,
         15.        ,  18.02775638],
       [ 22.36067977,  14.14213562,  14.14213562,  15.        ,
          0.        ,  10.        ],
       [ 28.28427125,  22.36067977,  22.36067977,  18.02775638,
         10.        ,   0.        ]])

In [51]:
tree = KDTree(points)

In [61]:
for point in points:
    print tree.query(point, 3)[0][2]

11.1803398875
11.1803398875
20.0
11.1803398875
14.1421356237
18.0277563773


In [9]:
w = Kernel(points, fixed=True, k=4.0, function='bisquare', diagonal=True)


TypeError: float() argument must be a string or a number