In [1]:
import numpy as np
import pandas as pd
import pysal as ps



from sel_bw import Sel_BW
from gwr import GWR
from pysal.contrib.glm.family import Poisson

from pysal.contrib.glm.glm import GLM
import statsmodels.api as sm
from pysal.contrib.glm.family import Poisson

In [2]:
data = ps.open(ps.examples.get_path('Tokyomortality.csv'), 'rU')
y = np.array(data.by_col('db2564')).reshape((-1,1))
a = np.array(data.by_col('OCC_TEC')).reshape((-1,1))
b = np.array(data.by_col('OWNH')).reshape((-1,1))
c = np.array(data.by_col('POP65')).reshape((-1,1))
d = np.array(data.by_col('UNEMP')).reshape((-1,1))
off = np.array(data.by_col('eb2564')).reshape((-1,1))

X = np.hstack([a,b,c,d])


#Coordinates for calibration points
u = data.by_col('X_CENTROID')
v = data.by_col('Y_CENTROID')
coords = zip(u,v)

In [3]:
#Instantiate bandwidth selection class - bisquare NN (adaptive)
sel = Sel_BW(coords, y, X, family=Poisson(), offset=off, kernel='bisquare', fixed=False)

#Find optimal bandwidth by minimizing AICc using golden section search algorithm
bw = sel.search(criterion='AICc')
print bw

50 131.0 262 181.0
384.603733031 373.549743374 392.320553232 384.604416054
50 100.0 181.0 131.0
384.603733031 367.10202563 384.604416054 373.549743374
50 81.0 131.0 100.0
384.603733031 366.208356318 373.549743374 367.10202563
50 69.0 100.0 81.0
384.603733031 369.801895208 367.10202563 366.208356318
69.0 81.0 100.0 88.0
369.801895208 366.208356318 367.10202563 366.193692867
81.0 88.0 100.0 93.0
366.208356318 366.193692867 367.10202563 365.878533889
88.0 93.0 100.0 95.0
366.193692867 365.878533889 367.10202563 365.472810347
93.0 95.0 100.0 97.0
365.878533889 365.472810347 367.10202563 366.121785738
93.0 95.0 97.0 95.0
365.878533889 365.472810347 366.121785738 365.472810347
95.0


In [180]:
model = GWR(coords, y, X, bw = 100, family=Poisson(), kernel='bisquare', fixed=False)
results = model.fit()

In [194]:
np.mean(results.params[:,4])

0.037879032722249337

In [183]:
endog = results.y
mu = results.mu

In [184]:
poiss=Poisson()

In [201]:
np.sum(poiss.resid_dev(endog, mu)**2)

17812.783000857915

In [202]:
#deviance
np.sum(results.resid_deviance**2)

17812.783000857915

In [204]:
np.sum(results.resid_response)

1250.1936048172699

In [207]:
np.sqrt(np.sum((endog-mu)**2))

2405.6405533701632

In [208]:
results.tr_S

25.269614576713266

In [209]:
results.tr_STS

18.476243776687351

In [213]:
results.null_deviance

51975.146607441435

In [216]:
#percent dev global
1 - 17812.783000857915/51975.146607441435

0.6572826790582327

In [3]:
model = GWR(coords, y, X, bw = 100, family=Poisson(), offset=off, kernel='bisquare', fixed=False)
results = model.fit()

In [4]:
endog = results.y
mu = results.mu

In [5]:
np.sum(results.resid_deviance**2)

311.23890351589222

In [6]:
results.null_deviance

960.24335197964797

In [7]:
1 - 1685985010.3257794/960.24335197979872

-1755788.3078350087

In [8]:
p = Poisson()

In [9]:
p.predict()

TypeError: predict() takes exactly 2 arguments (1 given)

In [38]:
model = GWR(coords, y, X, bw = 100, family=Poisson(), kernel='bisquare', fixed=False)
results = model.fit()

In [39]:
endog = results.y
mu = results.mu

In [40]:
np.sum(results.resid_deviance**2)

17812.783000857915

In [13]:
results.null_deviance

960.24335197964797

In [14]:
1 - 311.23890351589222/960.24335197964797

0.6758749718243414

In [15]:
np.mean(results.params[:,0])

0.038574755754217045

In [16]:
np.mean(results.params[:,1])

-2.1326067277287399

In [17]:
np.mean(results.params[:,2])

-0.27583401958630227

In [18]:
np.mean(results.params[:,3])

2.1695786445970224

In [19]:
np.mean(results.params[:,4])

0.047531701914650559

In [20]:
results.tr_S

25.144338923628634

In [21]:
results.pDev


array([[ 0.43016643],
       [ 0.33026011],
       [ 0.62595706],
       [ 0.25783817],
       [ 0.46695582],
       [ 0.68493002],
       [ 0.42742899],
       [ 0.56336641],
       [ 0.34302246],
       [ 0.57220432],
       [ 0.52745075],
       [ 0.51999517],
       [ 0.52623063],
       [ 0.62077062],
       [ 0.64281782],
       [ 0.57124744],
       [ 0.59457248],
       [ 0.43012915],
       [ 0.34986756],
       [ 0.57506562],
       [ 0.53182861],
       [ 0.27369578],
       [ 0.29485494],
       [ 0.33848467],
       [ 0.31398008],
       [ 0.35946826],
       [ 0.28403823],
       [ 0.35006974],
       [ 0.34976115],
       [ 0.63791352],
       [ 0.65684674],
       [ 0.69702563],
       [ 0.30474449],
       [ 0.32272632],
       [ 0.30816438],
       [ 0.28242651],
       [ 0.27528065],
       [ 0.28716499],
       [ 0.36203311],
       [ 0.26533797],
       [ 0.73862704],
       [ 0.6651594 ],
       [ 0.56432469],
       [ 0.28685119],
       [ 0.47576471],
       [ 0

In [22]:
results.deviance

506.85090181046797

In [23]:
results.D2

0.47216411260172875

In [24]:
1 - results.deviance/results.null_deviance

0.47216411260172875

In [25]:
(29.03125779 / (24641.32003671*off[0]))

array([  6.05510307e-06])

In [26]:
5569.04212701 

5569.04212701

In [27]:
24641.32003671

24641.32003671

In [28]:
24641.32003671*off[0]

array([ 4794510.92218274])

In [29]:
29.0/4794510.92218274

6.048583572064847e-06

In [30]:
1 - 29.0/55.0

0.4727272727272728

In [31]:
np.sqrt(226.90948533)

15.063515038994053

In [32]:
np.log(226.90948533)

5.4245511949226097

In [33]:
np.log(off[0])*262

array([ 1380.95019592])

In [34]:
off[0]

array([ 194.572])

In [35]:
np.sqrt(194.572)*226.90948533

3165.1392554611975

In [36]:
3165.1392554611975/1380.95019592

2.2920010184382913

In [39]:
np.log(50.0/10.0)

1.6094379124341003

In [40]:
off.T.shape

(1, 262)

In [41]:
results.predy

array([[  190.06917864],
       [   93.53236823],
       [   81.20774348],
       [   57.0423558 ],
       [   74.95401072],
       [  105.81678877],
       [   72.65543293],
       [   75.98696656],
       [  172.4538383 ],
       [   26.41484263],
       [   25.69625776],
       [   59.04198744],
       [   30.8276243 ],
       [   19.59342348],
       [   23.68289502],
       [   17.2950085 ],
       [   29.0480221 ],
       [   35.4390572 ],
       [   16.87182786],
       [   39.5106317 ],
       [   20.31001868],
       [   41.87214   ],
       [   15.53526158],
       [   38.19182403],
       [   64.61527256],
       [   14.97473326],
       [   49.37698912],
       [   26.88300774],
       [   44.29063128],
       [   40.98442075],
       [   44.26696663],
       [   26.27290623],
       [  122.11383778],
       [   28.99510474],
       [   18.19343483],
       [   18.68051609],
       [   43.02791862],
       [   37.31565455],
       [  397.93739897],
       [  219.01749013],


In [22]:
y = results.y
y_bar = results.y_bar
off = results.offset
off = np.tile(off, results.n).T
dev = np.zeros(shape=(results.n,1))
ones = np.ones(shape=(results.n,1))
for i in range(results.n):
    w_i= np.reshape(np.array(results.W[i]), (-1, 1))    
    for j in range(results.n):
        if results.y[j] <> 0:   
            dev[i] += 2.0 * w_i[j] * (y[j] * np.log(y[j]/(y_bar[i]*off[i][j])) - (y[j] - y_bar[i] * off[i][j])) 

   

In [23]:
dev

array([[  50.94690717],
       [  42.57890767],
       [  83.15005169],
       [  37.54430812],
       [  61.02893105],
       [ 102.5744406 ],
       [  53.37424174],
       [  70.5096139 ],
       [  45.48661326],
       [  71.91318024],
       [  62.55781096],
       [  63.17846518],
       [  66.34242779],
       [  86.61759467],
       [  92.20701906],
       [  71.14175569],
       [  76.96016263],
       [  45.25039539],
       [  43.06369959],
       [  74.78828441],
       [  69.63270524],
       [  39.14031342],
       [  42.01086486],
       [  46.98943887],
       [  41.57988749],
       [  46.06724957],
       [  38.94700839],
       [  47.73836483],
       [  46.29434271],
       [  87.53421897],
       [  93.95778009],
       [ 107.99701754],
       [  50.16682434],
       [  44.38180847],
       [  52.4386031 ],
       [  53.07167132],
       [  51.64081815],
       [  50.6018793 ],
       [  67.29900395],
       [  60.76571918],
       [ 140.0903085 ],
       [ 105.051

In [27]:
W = results.W
y = results.y
y_bar = results.y_bar
off = results.offset.T
#off = np.tile(off, results.n).T
dev = np.sum(2.0*W*(y*np.log(y/(y_bar*off))-(y-y_bar*off)),axis=1)


In [28]:
dev.reshape((-1,1))

array([[  50.94690717],
       [  42.57890767],
       [  83.15005169],
       [  37.54430812],
       [  61.02893105],
       [ 102.5744406 ],
       [  53.37424174],
       [  70.5096139 ],
       [  45.48661326],
       [  71.91318024],
       [  62.55781096],
       [  63.17846518],
       [  66.34242779],
       [  86.61759467],
       [  92.20701906],
       [  71.14175569],
       [  76.96016263],
       [  45.25039539],
       [  43.06369959],
       [  74.78828441],
       [  69.63270524],
       [  39.14031342],
       [  42.01086486],
       [  46.98943887],
       [  41.57988749],
       [  46.06724957],
       [  38.94700839],
       [  47.73836483],
       [  46.29434271],
       [  87.53421897],
       [  93.95778009],
       [ 107.99701754],
       [  50.16682434],
       [  44.38180847],
       [  52.4386031 ],
       [  53.07167132],
       [  51.64081815],
       [  50.6018793 ],
       [  67.29900395],
       [  60.76571918],
       [ 140.0903085 ],
       [ 105.051

In [30]:
off.shape

(1, 262)

In [10]:
import numpy as np
a = np.array([1,2,3,4,5]).reshape((-1,1))

In [14]:
np.repeat(a, 5).reshape((5,5)).T

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [13]:
np.tile(a,5).T

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [41]:
results.localR2

array([[ 0.66940126],
       [ 0.46403708],
       [ 0.65013845],
       [ 0.60508427],
       [ 0.65902707],
       [ 0.67508485],
       [ 0.60692175],
       [ 0.66331638],
       [ 0.66323473],
       [ 0.62246625],
       [ 0.62994048],
       [ 0.65792454],
       [ 0.69106137],
       [ 0.61944707],
       [ 0.61696325],
       [ 0.60708189],
       [ 0.59875195],
       [ 0.6337771 ],
       [ 0.66215957],
       [ 0.69554237],
       [ 0.68387309],
       [ 0.57578604],
       [ 0.61385305],
       [ 0.62211011],
       [ 0.49106667],
       [ 0.49355418],
       [ 0.53219217],
       [ 0.58197842],
       [ 0.53913841],
       [ 0.67372522],
       [ 0.67220985],
       [ 0.6361894 ],
       [ 0.4024205 ],
       [ 0.4319478 ],
       [ 0.40143185],
       [ 0.38584074],
       [ 0.37762007],
       [ 0.38751958],
       [ 0.20663525],
       [ 0.36875511],
       [ 0.39420301],
       [ 0.36082954],
       [ 0.36558913],
       [ 0.38412196],
       [ 0.18068839],
       [ 0

In [42]:
results.pDev

array([[ 0.7622257 ],
       [ 0.62726133],
       [ 0.77419007],
       [ 0.71605921],
       [ 0.76272344],
       [ 0.77958809],
       [ 0.72425869],
       [ 0.7764643 ],
       [ 0.75561805],
       [ 0.76097283],
       [ 0.75953811],
       [ 0.77018387],
       [ 0.7860378 ],
       [ 0.76306605],
       [ 0.76259748],
       [ 0.75475836],
       [ 0.75386888],
       [ 0.74529201],
       [ 0.74950488],
       [ 0.79104197],
       [ 0.78212027],
       [ 0.70326867],
       [ 0.72582176],
       [ 0.7345218 ],
       [ 0.64767963],
       [ 0.65192509],
       [ 0.67518191],
       [ 0.71140936],
       [ 0.68319375],
       [ 0.77176012],
       [ 0.78203163],
       [ 0.76655557],
       [ 0.57700787],
       [ 0.5941938 ],
       [ 0.57843592],
       [ 0.56492852],
       [ 0.5593949 ],
       [ 0.56543827],
       [ 0.34548077],
       [ 0.55825802],
       [ 0.42685125],
       [ 0.40917966],
       [ 0.45998372],
       [ 0.56967809],
       [ 0.23127793],
       [ 0