In [3]:
import numpy as np
import pysal
import os
os.chdir('/Users/toshan/projects/GIS596/pysal/pysal/contrib/gwr')
from kernels import *
import matplotlib

In [58]:
np.random.seed(1234)
x = np.arange(1,6)
y = np.arange(5,0, -1)



In [59]:
np.random.shuffle(x)
np.random.shuffle(y)

In [60]:
print x
print y

[5 1 2 3 4]
[2 3 4 5 1]


In [61]:
coords = np.array(zip(x,y))

In [62]:
coords

array([[5, 2],
       [1, 3],
       [2, 4],
       [3, 5],
       [4, 1]])

In [63]:
fix_gauss(coords, 3)

array([[ 1.        ,  0.38889556,  0.48567179,  0.48567179,  0.89483932],
       [ 0.38889556,  1.        ,  0.89483932,  0.64118039,  0.48567179],
       [ 0.48567179,  0.89483932,  1.        ,  0.89483932,  0.48567179],
       [ 0.48567179,  0.64118039,  0.89483932,  1.        ,  0.38889556],
       [ 0.89483932,  0.48567179,  0.48567179,  0.38889556,  1.        ]])

In [64]:
adapt_gauss(coords, 3)

array([[ 1.        ,  0.52004183,  0.60653072,  0.60653072,  0.92596109],
       [ 0.34559083,  1.        ,  0.88249692,  0.60653072,  0.44374738],
       [ 0.03877423,  0.60653072,  1.        ,  0.60653072,  0.03877423],
       [ 0.44374738,  0.60653072,  0.88249692,  1.        ,  0.34559083],
       [ 0.92596109,  0.60653072,  0.60653072,  0.52004183,  1.        ]])

In [65]:
fix_bisquare(coords, 3)

array([[ 1.        ,  0.        ,  0.        ,  0.        ,  0.60493827],
       [ 0.        ,  1.        ,  0.60493827,  0.01234568,  0.        ],
       [ 0.        ,  0.60493827,  1.        ,  0.60493827,  0.        ],
       [ 0.        ,  0.01234568,  0.60493827,  1.        ,  0.        ],
       [ 0.60493827,  0.        ,  0.        ,  0.        ,  1.        ]])

In [68]:
adapt_bisquare(coords, 3)

array([[  1.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          3.99999881e-14,   7.15976383e-01],
       [  0.00000000e+00,   1.00000000e+00,   5.62500075e-01,
          3.99999881e-14,   0.00000000e+00],
       [  0.00000000e+00,   3.99999881e-14,   1.00000000e+00,
          3.99999881e-14,   0.00000000e+00],
       [  0.00000000e+00,   3.99999881e-14,   5.62500075e-01,
          1.00000000e+00,   0.00000000e+00],
       [  7.15976383e-01,   0.00000000e+00,   3.99999881e-14,
          0.00000000e+00,   1.00000000e+00]])

In [69]:
fix_exp(coords, 3)

array([[ 1.        ,  0.2529993 ,  0.30063739,  0.30063739,  0.62412506],
       [ 0.2529993 ,  1.        ,  0.62412506,  0.38953209,  0.30063739],
       [ 0.30063739,  0.62412506,  1.        ,  0.62412506,  0.30063739],
       [ 0.30063739,  0.38953209,  0.62412506,  1.        ,  0.2529993 ],
       [ 0.62412506,  0.30063739,  0.30063739,  0.2529993 ,  1.        ]])

In [70]:
adapt_exp(coords, 3)

array([[ 1.        ,  0.31868771,  0.36787948,  0.36787948,  0.67554721],
       [ 0.23276223,  1.        ,  0.60653069,  0.36787948,  0.27949951],
       [ 0.07811997,  0.36787948,  1.        ,  0.36787948,  0.07811997],
       [ 0.27949951,  0.36787948,  0.60653069,  1.        ,  0.23276223],
       [ 0.67554721,  0.36787948,  0.36787948,  0.31868771,  1.        ]])