In [8]:
austria = pd.read_csv('http://dl.dropbox.com/u/8649795/AT_Austria.csv')
austria = austria[austria['Origin'] != austria['Destination']]
f = np.reshape(austria['Data'].values, (-1,1))
o = austria['Origin'].values
d = austria['Destination'].values
dij = np.reshape(austria['Dij'].values, (-1,1))
o_vars = np.reshape(austria['Oi2007'].values, (-1,1))
d_vars = np.reshape(austria['Dj2007'].values, (-1,1))
dij = np.reshape(austria['Dij'].values, (-1,1))
o_vars = np.reshape(austria['Oi2007'].values, (-1,1))
d_vars = np.reshape(austria['Dj2007'].values, (-1,1))

def newton(f, x0):
    # wrap scipy.optimize.newton with our automatic derivatives
    params = scipy.optimize.fsolve(f, x0)
    return params

def poiss_loglike(mu, sig, ep, x, inputs):
    a,b,c = inputs[:,0], inputs[:,1], inputs[:,2]
    predict = sig*a + ep*b + mu*c
    predict = np.reshape(predict, (-1,1))
    return -np.sum(x*np.log(predict)-predict)

#def loglike(mu, k, x, inputs):
    #return np.sum(poiss_loglike(mu, k, x, inputs))


def fit_maxlike(x, inputs, mu_guess, o_guess, d_guess):
    prime = lambda p: multigrad(poiss_loglike, argnums=[0,1,2])(p[0], p[1], p[2], x, inputs)
    params = newton(prime, (mu_guess, o_guess, d_guess))
    return params


if __name__ == "__main__":
    
    x=np.log(f)
    inputs = np.hstack((np.log(o_vars), np.log(d_vars), np.log(dij)))
    params = fit_maxlike(x, inputs, mu_guess=0.0, o_guess=1.0, d_guess=1.0)
    print(params)
    params = fit_maxlike(x, inputs, mu_guess=-1.14993102, o_guess=0.69084953, d_guess=0.68523832)
    print(params)
    
    prime = lambda p: multigrad(poiss_loglike, argnums=[0,1,2])(p[0], p[1], p[2], x, inputs)
    print(prime(params))




[ 0.35476854  0.25806804  0.23115129]
[ 0.35476854  0.25806804  0.23115129]
(1.958243558419781e-07, 4.8704197297411156e-07, 5.7569423006498255e-08)


array([[ 1131],
       [ 1887],
       [   69],
       [  738],
       [   98],
       [   31],
       [   43],
       [   19],
       [ 1633],
       [14055],
       [  416],
       [ 1276],
       [ 1850],
       [  388],
       [  303],
       [  159],
       [ 2301],
       [20164],
       [ 1080],
       [ 1831],
       [ 1943],
       [  742],
       [  674],
       [  407],
       [   85],
       [  379],
       [ 1597],
       [ 1608],
       [  328],
       [  317],
       [  469],
       [  114],
       [  762],
       [ 1110],
       [ 2973],
       [ 1252],
       [ 1081],
       [  622],
       [  425],
       [  262],
       [  196],
       [ 2027],
       [ 3498],
       [  346],
       [ 1332],
       [ 2144],
       [  821],
       [  274],
       [   49],
       [  378],
       [ 1349],
       [  310],
       [  851],
       [ 2117],
       [  630],
       [  106],
       [   87],
       [  424],
       [  978],
       [  490],
       [  670],
       [  577],
       [