In [1]:
import numpy as np
import pandas as pd
from gravity import Gravity, Production, Attraction, Doubly, BaseGravity
from entropy import Unconstrained, ProductionConstrained, AttractionConstrained, DoublyConstrained
import statsmodels.formula.api as smf
from statsmodels.api import families


In [2]:
austria = pd.read_csv('http://dl.dropbox.com/u/8649795/AT_Austria.csv')
austria = austria[austria['Origin'] != austria['Destination']]
f = austria['Data'].values
o = austria['Origin'].values
d = austria['Destination'].values
dij = austria['Dij'].values
o_vars = austria['Oi2007'].values
d_vars = austria['Dj2007'].values

In [3]:
gravity = Gravity(f, o_vars, d_vars, dij, 'exp', framework='sm_glm')
print gravity.params

gravity = Gravity(f, o_vars, d_vars, dij, 'exp', framework='glm')
print gravity.params

gravity = Unconstrained(austria, 'Origin', 'Destination', 'Data', ['Oi2007'] ,['Dj2007'], 'Dij', 'exp')
print gravity.p

gravity = smf.glm('Data~np.log(Oi2007)+np.log(Dj2007)+Dij-1', family=families.Poisson(), data=austria).fit()
print gravity.params.values

[ 0.44051324  0.5144978  -0.00976746]
[ 0.44051324  0.5144978  -0.00976746]
{'Dj2007': 0.5242653, 'beta': -0.0097675, 'Oi2007': 0.4502807}
[ 0.44051324  0.5144978  -0.00976746]


In [4]:
#production = Production(f, o, d_vars, dij, 'exp', framework='sm_glm')
#print production.params[-2:]

production = Production(f, o, d_vars, dij, 'exp', framework='glm')
print production.params[-2:]

production = ProductionConstrained(austria, 'Origin', 'Destination', 'Data', ['Dj2007'], 'Dij', 'exp')
print production.p

gravity = smf.glm('Data~Origin+np.log(Dj2007)+Dij', family=families.Poisson(), data=austria).fit()
print gravity.params.values[-2:]


[ 0.89278717 -0.00727113]
{'Dj2007': 0.9000583, 'beta': -0.0072711}
[ 0.89278717 -0.00727113]


In [5]:
#attraction = Attraction(f, d, o_vars, dij, 'exp')
#print attraction.params[-2:]

attraction = Attraction(f, d, o_vars, dij, 'exp', framework='glm')
print attraction.params[-2:]

attraction = AttractionConstrained(austria, 'Origin', 'Destination', 'Data', ['Oi2007'], 'Dij', 'exp')
print attraction.p

gravity = smf.glm('Data~np.log(Oi2007)+Destination + Dij', family=families.Poisson(), data=austria).fit()
print gravity.params.values[-2:]

[ 0.89235874 -0.00693755]
{'beta': -0.0069375, 'Oi2007': 0.8992963}
[ 0.89235874 -0.00693755]


In [6]:
#doubly = Doubly(f, o, d, dij, 'exp')
#print doubly.params[-1]


doubly = Doubly(f, o, d, dij, 'exp', framework='glm')
print doubly.params[-1]

doubly = DoublyConstrained(austria, 'Origin', 'Destination', 'Data', 'Dij', 'exp')
print doubly.p

gravity = smf.glm('Data~Origin+Destination+Dij-1', family=families.Poisson(), data=austria).fit()
print gravity.params.values[-1]


-0.0079153331097
{'beta': -0.0079153}
-0.0079153331611


/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scipy/optimize/minpack.py:237: RuntimeWarning: The iteration is not making good progress, as measured by the 
  improvement from the last ten iterations.
  warnings.warn(msg, RuntimeWarning)
