In [11]:
import numpy as np
from pointpattern import PointPattern
points = [[66.22, 32.54], [22.52, 22.39], [31.01, 81.21], [9.47, 31.02],
               [30.78, 60.10], [75.21, 58.93], [79.26,  7.68], [8.23, 39.93],
               [98.73, 80.53], [89.78, 42.53], [65.19, 92.08], [54.46, 8.48]]

In [12]:
from centrography import hull, mbr, mean_center, weighted_mean_center, manhattan_median

In [13]:
pp = PointPattern(points)
hull(pp.points)

array([[ 31.01,  81.21],
       [  8.23,  39.93],
       [  9.47,  31.02],
       [ 22.52,  22.39],
       [ 54.46,   8.48],
       [ 79.26,   7.68],
       [ 89.78,  42.53],
       [ 98.73,  80.53],
       [ 65.19,  92.08]])

In [14]:
mbr(pp.points)

(8.2300000000000004,
 7.6799999999999997,
 98.730000000000004,
 92.079999999999998)

In [15]:
mean_center(pp.points)

In [16]:
manhattan_median(pp.points)

array([ 59.825,  41.23 ])

In [17]:
np.median(points, axis=0)

array([ 59.825,  41.23 ])

In [18]:
points = np.array(points)

In [19]:
points

array([[ 66.22,  32.54],
       [ 22.52,  22.39],
       [ 31.01,  81.21],
       [  9.47,  31.02],
       [ 30.78,  60.1 ],
       [ 75.21,  58.93],
       [ 79.26,   7.68],
       [  8.23,  39.93],
       [ 98.73,  80.53],
       [ 89.78,  42.53],
       [ 65.19,  92.08],
       [ 54.46,   8.48]])

In [20]:
weights = np.arange(12)
weighted_mean_center(pp.points, weights)

array([ 60.51681818,  48.17575758])